load('renameListValue.js');

var toReplace = [
    ["ACT - Alpine Sphagnum Bogs and Associated Fens", "Alpine Sphagnum Bogs and Associated Fens"],
    ["ACT - Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory", "Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory"],
    ["ACT - White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland"],
    ["NSW - Alpine Sphagnum Bogs and Associated Fens", "Alpine Sphagnum Bogs and Associated Fens"],
    ["NSW - Blue Gum High Forest of the Sydney Basin Bioregion", "Blue Gum High Forest of the Sydney Basin Bioregion"],
    ["NSW - Brigalow (Acacia harpophylla dominant and co-dominant)", "Brigalow (Acacia harpophylla dominant and co-dominant)"],
    ["NSW - Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions", "Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions"],
    ["NSW - Coolibah - Black Box Woodlands of the Darling Riverine Plains and the Brigalow Belt South Bioregions", "Coolibah - Black Box Woodlands of the Darling Riverine Plains and the Brigalow Belt South Bioregions"],
    ["NSW - Cumberland Plain Shale Woodlands and Shale-Gravel Transition Forest", "Cumberland Plain Shale Woodlands and Shale-Gravel Transition Forest"],
    ["NSW - Eastern Suburbs Banksia Scrub of the Sydney Region", "Eastern Suburbs Banksia Scrub of the Sydney Region"],
    ["NSW - Giant Kelp Marine Forests of South East Australia", "Giant Kelp Marine Forests of South East Australia"],
    ["NSW - Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia", "Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia"],
    ["NSW - Littoral Rainforest and Coastal Vine Thickets of Eastern Australia", "Littoral Rainforest and Coastal Vine Thickets of Eastern Australia"],
    ["NSW - Lowland Grassy Woodland in the South East Corner Bioregion", "Lowland Grassy Woodland in the South East Corner Bioregion"],
    ["NSW - Lowland Rainforest of Subtropical Australia", "Lowland Rainforest of Subtropical Australia"],
    ["NSW - Natural Grasslands of the Murray Valley Plains", "Natural Grasslands of the Murray Valley Plains"],
    ["NSW - Natural grasslands on basalt and fine-textured alluvial plains of northern New South Wales and southern Queensland", "Natural grasslands on basalt and fine-textured alluvial plains of northern New South Wales and southern Queensland"],
    ["NSW - Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory", "Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory"],
    ["NSW - New England Peppermint (Eucalyptus nova-anglica) Grassy Woodlands", "New England Peppermint (Eucalyptus nova-anglica) Grassy Woodlands"],
    ["NSW - River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea", "River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea"],
    ["NSW - Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains", "Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains"],
    ["NSW - Semi-evergreen vine thickets of the Brigalow Belt (North and South) and Nandewar Bioregions", "Semi-evergreen vine thickets of the Brigalow Belt (North and South) and Nandewar Bioregions"],
    ["NSW - Shale/Sandstone Transition Forest", "Shale/Sandstone Transition Forest"],
    ["NSW - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["NSW - Temperate Highland Peat Swamps on Sandstone", "Temperate Highland Peat Swamps on Sandstone"],
    ["NSW - The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin", "The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin"],
    ["NSW - Turpentine-Ironbark Forest in the Sydney Basin Bioregion", "Turpentine-Ironbark Forest in the Sydney Basin Bioregion"],
    ["NSW - Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion", "Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion"],
    ["NSW - Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion", "Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion"],
    ["NSW - Upland Wetlands of the New England Tablelands and the Monaro Plateau", "Upland Wetlands of the New England Tablelands and the Monaro Plateau"],
    ["NSW - Hunter Valley Weeping Myall (Acacia pendula) Woodland", "Hunter Valley Weeping Myall (Acacia pendula) Woodland"],
    ["NSW - Weeping Myall Woodlands", "Weeping Myall Woodlands"],
    ["NSW - Western Sydney Dry Rainforest and Moist Woodland on Shale", "Western Sydney Dry Rainforest and Moist Woodland on Shale"],
    ["NSW - Wetlands and inner floodplains of the Macquarie Marshes", "Wetlands and inner floodplains of the Macquarie Marshes"],
    ["NSW - White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland"],
    ["NT - Arnhem Plateau Sandstone Shrubland Complex", "Arnhem Plateau Sandstone Shrubland Complex"],
    ["QLD - Brigalow (Acacia harpophylla dominant and co-dominant)", "Brigalow (Acacia harpophylla dominant and co-dominant)"],
    ["QLD - Broad leaf tea-tree (Melaleuca viridiflora) woodlands in high rainfall coastal north Queensland", "Broad leaf tea-tree (Melaleuca viridiflora) woodlands in high rainfall coastal north Queensland"],
    ["QLD - Coolibah - Black Box Woodlands of the Darling Riverine Plains and the Brigalow Belt South Bioregions", "Coolibah - Black Box Woodlands of the Darling Riverine Plains and the Brigalow Belt South Bioregions"],
    ["QLD - Littoral Rainforest and Coastal Vine Thickets of Eastern Australia", "Littoral Rainforest and Coastal Vine Thickets of Eastern Australia"],
    ["QLD - Lowland Rainforest of Subtropical Australia", "Lowland Rainforest of Subtropical Australia"],
    ["QLD - Mabi Forest (Complex Notophyll Vine Forest 5b)", "Mabi Forest (Complex Notophyll Vine Forest 5b)"],
    ["QLD - Natural Grasslands of the Queensland Central Highlands and the northern Fitzroy Basin", "Natural Grasslands of the Queensland Central Highlands and the northern Fitzroy Basin"],
    ["QLD - Natural grasslands on basalt and fine-textured alluvial plains of northern New South Wales and southern Queensland", "Natural grasslands on basalt and fine-textured alluvial plains of northern New South Wales and southern Queensland"],
    ["QLD - New England Peppermint (Eucalyptus nova-anglica) Grassy Woodlands", "New England Peppermint (Eucalyptus nova-anglica) Grassy Woodlands"],
    ["QLD - Semi-evergreen vine thickets of the Brigalow Belt (North and South) and Nandewar Bioregions", "Semi-evergreen vine thickets of the Brigalow Belt (North and South) and Nandewar Bioregions"],
    ["QLD - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["QLD - Swamp Tea-tree (Melaleuca irbyana) Forest of South-east Queensland", "Swamp Tea-tree (Melaleuca irbyana) Forest of South-east Queensland"],
    ["QLD - The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin", "The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin"],
    ["QLD - Weeping Myall Scrub Wilga Shrubland of the Hunter Valley", "Weeping Myall Scrub Wilga Shrubland of the Hunter Valley"],
    ["QLD - White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland"],
    ["SA - Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions", "Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions"],
    ["SA - Eyre Peninsula Blue Gum (Eucalyptus petiolaris) Woodland", "Eyre Peninsula Blue Gum (Eucalyptus petiolaris) Woodland"],
    ["SA - Giant Kelp Marine Forests of South East Australia", "Giant Kelp Marine Forests of South East Australia"],
    ["SA - Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia", "Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia"],
    ["SA - Iron-grass Natural Temperate Grassland of South Australia", "Iron-grass Natural Temperate Grassland of South Australia"],
    ["SA - Kangaroo Island Narrow-leaved Mallee (Eucalyptus cneorifolia) Woodland", "Kangaroo Island Narrow-leaved Mallee (Eucalyptus cneorifolia) Woodland"],
    ["SA - Natural Grasslands of the Murray Valley Plains", "Natural Grasslands of the Murray Valley Plains"],
    ["SA - Peppermint Box (Eucalyptus odorata) Grassy Woodland of South Australia", "Peppermint Box (Eucalyptus odorata) Grassy Woodland of South Australia"],
    ["SA - River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea", "River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea"],
    ["SA - Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains", "Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains"],
    ["SA - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["SA - Swamps of the Fleurieu Peninsula", "Swamps of the Fleurieu Peninsula"],
    ["SA - The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin", "The community of native species dependent on natural discharge of groundwater from the Great Artesian Basin"],
    ["SA - White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland"],
    ["TAS - Alpine Sphagnum Bogs and Associated Fens", "Alpine Sphagnum Bogs and Associated Fens"],
    ["TAS - Eucalyptus ovata - Callitris oblonga Forest", "Eucalyptus ovata - Callitris oblonga Forest"],
    ["TAS - Giant Kelp Marine Forests of South East Australia", "Giant Kelp Marine Forests of South East Australia"],
    ["TAS - Lowland Native Grasslands of Tasmania", "Lowland Native Grasslands of Tasmania"],
    ["TAS - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["VIC - Alpine Sphagnum Bogs and Associated Fens", "Alpine Sphagnum Bogs and Associated Fens"],
    ["VIC - Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions", "Buloke Woodlands of the Riverina and Murray-Darling Depression Bioregions"],
    ["VIC - Giant Kelp Marine Forests of South East Australia", "Giant Kelp Marine Forests of South East Australia"],
    ["VIC - Gippsland Red Gum (Eucalyptus tereticornis subsp. mediana) Grassy Woodland and Associated Native Grassland", "Gippsland Red Gum (Eucalyptus tereticornis subsp. mediana) Grassy Woodland and Associated Native Grassland"],
    ["VIC - Grassy Eucalypt Woodland of the Victorian Volcanic Plain", "Grassy Eucalypt Woodland of the Victorian Volcanic Plain"],
    ["VIC - Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia", "Grey Box (Eucalyptus microcarpa) Grassy Woodlands and Derived Native Grasslands of South-eastern Australia"],
    ["VIC - Littoral Rainforest and Coastal Vine Thickets of Eastern Australia", "Littoral Rainforest and Coastal Vine Thickets of Eastern Australia"],
    ["VIC - Lowland Grassy Woodland in the South East Corner Bioregion", "Lowland Grassy Woodland in the South East Corner Bioregion"],
    ["VIC - Natural Grasslands of the Murray Valley Plains", "Natural Grasslands of the Murray Valley Plains"],
    ["VIC - Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory", "Natural Temperate Grassland of the Southern Tablelands of NSW and the Australian Capital Territory"],
    ["VIC - Natural Temperate Grassland of the Victorian Volcanic Plain", "Natural Temperate Grassland of the Victorian Volcanic Plain"],
    ["VIC - River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea", "River Murray and associated wetlands, floodplains and groundwater systems, from the junction with the Darling River to the sea"],
    ["VIC - Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains", "Seasonal Herbaceous Wetlands (Freshwater) of the Temperate Lowland Plains"],
    ["VIC - Silurian Limestone Pomaderris Shrubland of the South East Corner and Australian Alps Bioregions", "Silurian Limestone Pomaderris Shrubland of the South East Corner and Australian Alps Bioregions"],
    ["VIC - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["VIC - Temperate Highland Peat Swamps on Sandstone Weeping Myall Woodlands", "Temperate Highland Peat Swamps on Sandstone Weeping Myall Woodlands"],
    ["VIC - White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland"],
    ["WA - Aquatic Root Mat Community 1 in Caves of the Leeuwin Naturaliste Ridge", "Aquatic Root Mat Community 1 in Caves of the Leeuwin Naturaliste Ridge"],
    ["WA - Aquatic Root Mat Community 2 in Caves of the Leeuwin Naturaliste Ridge", "Aquatic Root Mat Community 2 in Caves of the Leeuwin Naturaliste Ridge"],
    ["WA - Aquatic Root Mat Community 3 in Caves of the Leeuwin Naturaliste Ridge", "Aquatic Root Mat Community 3 in Caves of the Leeuwin Naturaliste Ridge"],
    ["WA - Aquatic Root Mat Community 4 in Caves of the Leeuwin Naturaliste Ridge", "Aquatic Root Mat Community 4 in Caves of the Leeuwin Naturaliste Ridge"],
    ["WA - Aquatic Root Mat Community in Caves of the Swan Coastal Plain", "Aquatic Root Mat Community in Caves of the Swan Coastal Plain"],
    ["WA - Assemblages of plants and invertebrate animals of tumulus (organic mound) springs of the Swan Coastal Plain", "Assemblages of plants and invertebrate animals of tumulus (organic mound) springs of the Swan Coastal Plain"],
    ["WA - Claypans of the Swan Coastal Plain", "Claypans of the Swan Coastal Plain"],
    ["WA - Corymbia calophylla - Kingia australis woodlands on heavy soils of the Swan Coastal Plain", "Corymbia calophylla - Kingia australis woodlands on heavy soils of the Swan Coastal Plain"],
    ["WA - Corymbia calophylla - Xanthorrhoea preissii woodlands and shrublands of the Swan Coastal Plain", "Corymbia calophylla - Xanthorrhoea preissii woodlands and shrublands of the Swan Coastal Plain"],
    ["WA - Eastern Stirling Range Montane Heath and Thicket", "Eastern Stirling Range Montane Heath and Thicket"],
    ["WA - Monsoon vine thickets on the coastal sand dunes of Dampier Peninsula", "Monsoon vine thickets on the coastal sand dunes of Dampier Peninsula"],
    ["WA - Perched Wetlands of the Wheatbelt region with extensive stands of living sheoak and paperbark across the lake floor (Toolibin Lake)", "Perched Wetlands of the Wheatbelt region with extensive stands of living sheoak and paperbark across the lake floor (Toolibin Lake)"],
    ["WA - Scott River Ironstone Association", "Scott River Ironstone Association"],
    ["WA - Sedgelands in Holocene dune swales of the southern Swan Coastal Plain", "Sedgelands in Holocene dune swales of the southern Swan Coastal Plain"],
    ["WA - Shrublands and Woodlands of the eastern Swan Coastal Plain", "Shrublands and Woodlands of the eastern Swan Coastal Plain"],
    ["WA - Shrublands and Woodlands on Muchea Limestone of the Swan Coastal Plain", "Shrublands and Woodlands on Muchea Limestone of the Swan Coastal Plain"],
    ["WA - Shrublands and Woodlands on Perth to Gingin ironstone (Perth to Gingin ironstone association) of the Swan Coastal Plain", "Shrublands and Woodlands on Perth to Gingin ironstone (Perth to Gingin ironstone association) of the Swan Coastal Plain"],
    ["WA - Shrublands on southern Swan Coastal Plain ironstones", "Shrublands on southern Swan Coastal Plain ironstones"],
    ["WA - Subtropical and Temperate Coastal Saltmarsh", "Subtropical and Temperate Coastal Saltmarsh"],
    ["WA - Thrombolite (microbial) community of coastal freshwater lakes of the Swan Coastal Plain (Lake Richmond)", "Thrombolite (microbial) community of coastal freshwater lakes of the Swan Coastal Plain (Lake Richmond)"],
    ["WA - Thrombolite (microbialite) Community of a Coastal Brackish Lake (Lake Clifton)", "Thrombolite (microbialite) Community of a Coastal Brackish Lake (Lake Clifton)"]
];

for (var i = 0; i < toReplace.length; i++) {
    renameListValue('Conservation Works Details', 'targetTEC', toReplace[i][0], toReplace[i][1]);
}
