rsync -r ../../models/espBiomassControlMeasures fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espControlOfAgrochemicals fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espFencingActivities fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espFencingPaddockTrees fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espFeralAnimalManagement fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espGroundCover fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espLivestockGrazingManagement fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espNativeHerbivoreManagement fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espOptionalReporting fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espOverview fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espPlantSurvival fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espPmuZoneReporting fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espRegeneration fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espRestorationOfHabitatFeatures fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espRevegetation fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espSmuHeader fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espTreeRootDisturbances fieldcapture-test.ala.org.au:/home/god08d/esp/
rsync -r ../../models/espWeedManagement fieldcapture-test.ala.org.au:/home/god08d/esp/
