load("uuid.js");


var now = ISODate();

var nswSite = {
    "dateCreated" : now,
    "isSciStarter" : false,
    "lastUpdated" : now,
    "siteId" : UUID.generate(),
    "status" : "active",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 802948.463849786,
            "lga" : [
                "Corowa Shire (A)",
                "Ryde (C)",
                "Hay (A)",
                "Cooma-Monaro (A)",
                "Coonamble (A)",
                "Yass Valley (A)",
                "Murray (A)",
                "Young (A)",
                "Wingecarribee (A)",
                "Burwood (A)",
                "East Gippsland (S)",
                "Eurobodalla (A)",
                "Kogarah (C)",
                "Maitland (C)",
                "Manly (A)",
                "Goulburn Mulwaree (A)",
                "Cabonne (A)",
                "Wyong (A)",
                "Sydney (C)",
                "Cootamundra (A)",
                "Deniliquin (A)",
                "Indigo (S)",
                "Wentworth (A)",
                "Scenic Rim (R)",
                "Campaspe (S)",
                "Fairfield (C)",
                "Campbelltown (C) (ACT)",
                "Lithgow (C)",
                "Greater Taree (C)",
                "Gundagai (A)",
                "Gosford (C)",
                "Forbes (A)",
                "Wollondilly (A)",
                "Lake Macquarie (C)",
                "Leeton (A)",
                "Liverpool (C)",
                "Lane Cove (A)",
                "Dungog (A)",
                "Great Lakes (A)",
                "Guyra (A)",
                "Gunnedah (A)",
                "Strathfield (A)",
                "Narrandera (A)",
                "Lachlan (A)",
                "Wodonga (RC)",
                "Wollongong (C)",
                "Waverley (A)",
                "Weddin (A)",
                "Glen Innes Severn (A)",
                "Pittwater (A)",
                "Greater Hume Shire (A)",
                "Harden (A)",
                "Oberon (A)",
                "Woollahra (A)",
                "Richmond Valley (A)",
                "North Sydney (A)",
                "Wagga Wagga (C)",
                "Warren (A)",
                "Southern Downs (R)",
                "Tumut Shire (A)",
                "Marrickville (A)",
                "Lockhart (A)",
                "Hawkesbury (C)",
                "Orange (C)",
                "Palerang (A)",
                "Canterbury (C)",
                "Wellington (A)",
                "Willoughby (C)",
                "Central Darling (A)",
                "Cessnock (C)",
                "Clarence Valley (A)",
                "Coffs Harbour (C)",
                "Cobar (A)",
                "Armidale Dumaresq (A)",
                "Ashfield (A)",
                "Muswellbrook (A)",
                "Narrabri (A)",
                "Nambucca (A)",
                "Parkes (A)",
                "Parramatta (C)",
                "Penrith (C)",
                "Port Stephens (A)",
                "Port Macquarie-Hastings (A)",
                "Queanbeyan (C)",
                "Randwick (C)",
                "Gilgandra (A)",
                "Conargo (A)",
                "Auburn (C)",
                "Rockdale (C)",
                "Shoalhaven (C)",
                "Singleton (A)",
                "Snowy River (A)",
                "Sutherland Shire (A)",
                "Swan Hill (RC)",
                "Tamworth Regional (A)",
                "Tenterfield (A)",
                "Temora (A)",
                "Bathurst Regional (A)",
                "Berrigan (A)",
                "Albury (C)",
                "Byron (A)",
                "Ku-ring-gai (A)",
                "Lismore (C)",
                "Leichhardt (A)",
                "Blue Mountains (C)",
                "Blayney (A)",
                "Bogan (A)",
                "Boorowa (A)",
                "Bombala (A)",
                "Brewarrina (A)",
                "Bourke (A)",
                "Botany Bay (C)",
                "Camden (A)",
                "Cowra (A)",
                "Canada Bay (A)",
                "Goondiwindi (R)",
                "Gloucester (A)",
                "Gold Coast (C)",
                "Gwydir (A)",
                "Hornsby (A)",
                "Holroyd (C)",
                "Inverell (A)",
                "Jerilderie (A)",
                "Junee (A)",
                "Bellingen (A)",
                "Blacktown (C)",
                "Bega Valley (A)",
                "Newcastle (C)",
                "Kiama (A)",
                "Hurstville (C)",
                "Griffith (C)",
                "Carrathool (A)",
                "Bland (A)",
                "Kempsey (A)",
                "Shellharbour (C)",
                "Uralla (A)",
                "Liverpool Plains (A)",
                "Broken Hill (C)",
                "Dubbo (C)",
                "Narromine (A)",
                "Hunters Hill (A)",
                "Mid-Western Regional (A)",
                "Moira (S)",
                "Mildura (RC)",
                "Gannawarra (S)",
                "Moree Plains (A)",
                "Kyogle (A)",
                "The Hills Shire (A)",
                "Tumbarumba (A)",
                "Towong (S)",
                "Unincorp. Other Territories",
                "Tweed (A)",
                "Unincorporated SA",
                "Unincorporated NSW",
                "Upper Lachlan Shire (A)",
                "Upper Hunter Shire (A)",
                "Unincorporated ACT",
                "Coolamon (A)",
                "Wakool (A)",
                "Walgett (A)",
                "Walcha (A)",
                "Balranald (A)",
                "Ballina (A)",
                "Balonne (S)",
                "Bankstown (C)",
                "Murrumbidgee (A)",
                "Warringah (A)",
                "Warrumbungle Shire (A)",
                "Mosman (A)",
                "Urana (A)"
            ],
            "name" : "New South Wales",
            "nrm" : [
                "Marine NRM",
                "Western",
                "South East Queensland",
                "South East NSW",
                "North East",
                "North Coast - Lord Howe Island",
                "Northern Tablelands",
                "South Australian Murray Darling Basin",
                "South Australian Arid Lands",
                "Riverina",
                "North West NSW",
                "North Coast",
                "North Central",
                "Murray",
                "Mallee",
                "Hunter",
                "Greater Sydney",
                "Goulburn Broken",
                "East Gippsland",
                "Condamine",
                "Central West",
                "Central Tablelands",
                "Maranoa Balonne and Border Rivers",
                "ACT"
            ],
            "locality" : "",
            "centre" : [
                "147.00656430358598",
                "-32.1662650240896"
            ],
            "aream2" : 801831731283.5034,
            "pid" : "3742605",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Australian Capital Territory",
                "Jervis Bay Territory",
                "New South Wales (including Coastal Waters)",
                "South Australia (including Coastal Waters)",
                "Victoria (including Coastal Waters)",
                "Queensland (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Broken Hill Complex",
                "Mulga Lands",
                "Nandewar",
                "Riverina",
                "Australian Alps",
                "South Eastern Highlands",
                "South East Corner",
                "Murray Darling Depression",
                "Brigalow Belt South",
                "Simpson Strzelecki Dunefields",
                "Cobar Peneplain",
                "NSW South Western Slopes",
                "New England Tablelands",
                "Sydney Basin",
                "NSW North Coast",
                "Darling Riverine Plains",
                "Channel Country",
                "South Eastern Queensland"
            ],
            "imcra4_pb" : [
                "Central Eastern Shelf Province",
                "Southeast Shelf Transition",
                "Central Eastern Shelf Transition",
                "Lord Howe Province"
            ],
            "elect" : [
                "INDI",
                "NICHOLLS",
                "MALLEE",
                "MCPHERSON",
                "GREY",
                "MARANOA",
                "GILMORE",
                "WHITLAM",
                "HUME",
                "CUNNINGHAM",
                "HUGHES",
                "COOK",
                "MACARTHUR",
                "FARRER",
                "BARTON",
                "BANKS",
                "KINGSFORD SMITH",
                "NORTH SYDNEY",
                "WARRINGAH",
                "BENNELONG",
                "PARRAMATTA",
                "WERRIWA",
                "FOWLER",
                "MCMAHON",
                "BRADFIELD",
                "MACKELLAR",
                "BEROWRA",
                "GREENWAY",
                "CHIFLEY",
                "MITCHELL",
                "LINDSAY",
                "ROBERTSON",
                "MACQUARIE",
                "DOBELL",
                "WATSON",
                "BLAXLAND",
                "WENTWORTH",
                "SHORTLAND",
                "CALARE",
                "RIVERINA",
                "NEWCASTLE",
                "PATERSON",
                "HUNTER",
                "PARKES",
                "REID",
                "EDEN-MONARO",
                "LYNE",
                "NEW ENGLAND",
                "COWPER",
                "PAGE",
                "SYDNEY",
                "GRAYNDLER",
                "RICHMOND",
                "CANBERRA",
                "FENNER",
                "BEAN",
                "WRIGHT",
                "BARKER",
                "GIPPSLAND"
            ],
            "cmz" : [
                "Eastern Australia mulga shrublands",
                "Brigalow woodlands",
                "Eastern Australia tropical rainforests",
                "Eastern Australia woodlands",
                "Eastern Australia temperate and subtropical forests",
                "South Eastern Australia mallee woodlands",
                "South Eastern Australia mixed temperate forests woodlands and grasslands",
                "Arid shrublands and desert",
                "South Eastern Australia temperate woodlands",
                "Australian Alps montane grasslands and heathlands"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "RAMSAR wetland regions",
                "Directory of Important Wetlands",
                "ACT TAMS Reserves",
                "NSW Local Land Services Regions",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Atlas of Life in the Coastal Wilderness",
                "Great Eastern Ranges Initiative",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements"
            ],
            "gerSubRegion" : [
                "GER Border Ranges",
                "GER Illawarra to Shoalhaven",
                "GER Southern Highlands",
                "GER Hunter Valley",
                "GER Jaliigirr",
                "GER Central Victorial Biolinks",
                "GER Kosciuszko to Coast",
                "GER Slopes To Summit",
                "GER Victorian BioLinks"
            ]
        },
        "source" : "pid"
    },
    "name" : "New South Wales",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};
var saState = {
    "dateCreated" : ISODate("2020-03-12T22:48:20.021Z"),
    "isSciStarter" : false,
    "lastUpdated" : ISODate("2020-03-12T22:48:47.357Z"),
    "siteId" : UUID.generate(),
    "status" : "active",
    "address" : "",
    "nrm" : "",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "state" : "",
    "area" : "",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 986564.4158071108,
            "lga" : [
                "Tea Tree Gully (C)",
                "Diamantina (S)",
                "Elliston (DC)",
                "Mallala (DC)",
                "MacDonnell (S)",
                "Marion (C)",
                "Goyder (DC)",
                "West Torrens (C)",
                "Kingston (DC)",
                "Campbelltown (C) (SA)",
                "Adelaide Hills (DC)",
                "Laverton (S)",
                "Wudinna (DC)",
                "Mount Barker (DC)",
                "Dundas (S)",
                "Cleve (DC)",
                "Northern Areas (DC)",
                "Yankalilla (DC)",
                "Copper Coast (DC)",
                "Southern Mallee (DC)",
                "The Coorong (DC)",
                "Peterborough (DC)",
                "Norwood Payneham St Peters (C)",
                "Onkaparinga (C)",
                "Ngaanyatjarraku (S)",
                "Yorke Peninsula (DC)",
                "Clare and Gilbert Valleys (DC)",
                "Tatiara (DC)",
                "Adelaide (C)",
                "Anangu Pitjantjatjara (AC)",
                "Murray Bridge (RC)",
                "Naracoorte and Lucindale (DC)",
                "Playford (C)",
                "Port Adelaide Enfield (C)",
                "Port Augusta (C)",
                "Port Pirie City and Dists (M)",
                "Prospect (C)",
                "Renmark Paringa (DC)",
                "Ceduna (DC)",
                "Robe (DC)",
                "Salisbury (C)",
                "Berri and Barmera (DC)",
                "Streaky Bay (DC)",
                "Barossa (DC)",
                "Flinders Ranges (DC)",
                "Barunga West (DC)",
                "Burnside (C)",
                "Light (RegC)",
                "Holdfast Bay (C)",
                "Kangaroo Island (DC)",
                "Lower Eyre Peninsula (DC)",
                "Loxton Waikerie (DC)",
                "Unley (C)",
                "Mitcham (C)",
                "Charles Sturt (C)",
                "Roxby Downs (M)",
                "Coober Pedy (DC)",
                "Orroroo/Carrieton (DC)",
                "Gawler (T)",
                "Port Lincoln (C)",
                "Alexandrina (DC)",
                "Karoonda East Murray (DC)",
                "Victor Harbor (C)",
                "Maralinga Tjarutja (AC)",
                "Grant (DC)",
                "Franklin Harbour (DC)",
                "Mount Remarkable (DC)",
                "Kimba (DC)",
                "Kalgoorlie/Boulder (C)",
                "Mount Gambier (C)",
                "Mildura (RC)",
                "Mid Murray (DC)",
                "Tumby Bay (DC)",
                "Unincorporated SA",
                "Wakefield (DC)",
                "Walkerville (M)",
                "Wattle Range (DC)",
                "Whyalla (C)",
                "Menzies (S)"
            ],
            "name" : "South Australia",
            "nrm" : [
                "Marine NRM",
                "Rangelands Region",
                "Northern Territory",
                "South East",
                "South Australian Murray Darling Basin",
                "South Australian Arid Lands",
                "Northern and Yorke",
                "Mallee",
                "Kangaroo Island",
                "Eyre Peninsula",
                "Desert Channels",
                "Alinytjara Wilurara",
                "Adelaide and Mount Lofty Ranges"
            ],
            "locality" : "",
            "centre" : [
                "135.82719986112875",
                "-30.104682404350353"
            ],
            "aream2" : 985286636064.5944,
            "pid" : "3742600",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Western Australia (including Coastal Waters)",
                "Northern Territory (including Coastal Waters)",
                "South Australia (including Coastal Waters)",
                "Victoria (including Coastal Waters)",
                "Queensland (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Broken Hill Complex",
                "Kanmantoo",
                "Riverina",
                "Central Ranges",
                "Murray Darling Depression",
                "Naracoorte Coastal Plain",
                "Simpson Strzelecki Dunefields",
                "Victorian Volcanic Plain",
                "Finke",
                "Great Victoria Desert",
                "Flinders Lofty Block",
                "Eyre Yorke Block",
                "Hampton",
                "Gawler",
                "Channel Country",
                "Nullarbor",
                "Stony Plains"
            ],
            "imcra4_pb" : [
                "Great Australian Bight Shelf Transition",
                "Spencer Gulf Shelf Province",
                "Western Bass Strait Shelf Transition"
            ],
            "elect" : [
                "O'CONNOR",
                "MALLEE",
                "KINGSTON",
                "BOOTHBY",
                "STURT",
                "ADELAIDE",
                "MAKIN",
                "HINDMARSH",
                "SPENCE",
                "MAYO",
                "GREY",
                "MARANOA",
                "BARKER",
                "LINGIARI"
            ],
            "cmz" : [
                "Naracoorte woodlands",
                "South Eastern Australia mallee woodlands",
                "Arid shrublands and desert",
                "South Australian Eucalypt woodlands"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "Directory of Important Wetlands",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements"
            ],
            "gerSubRegion" : [ ]
        },
        "source" : "pid"
    },
    "name" : "South Australia",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};
var tasState ={
    "_id" : ObjectId("5e6abff7c2dc5f92fd0dc00e"),
    "dateCreated" : ISODate("2020-03-12T23:04:28.874Z"),
    "isSciStarter" : false,
    "lastUpdated" : ISODate("2020-03-12T23:04:48.442Z"),
    "projects" : [
        "d4cff543-0923-4bb6-a11c-4dfd9d64a7c6"
    ],
    "siteId" : "37cc85a0-2119-4b65-9ebf-ba75a9ba5ffd",
    "status" : "active",
    "address" : "",
    "nrm" : "",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "state" : "",
    "area" : "",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 68332.69688982605,
            "lga" : [
                "Dorset (M)",
                "George Town (M)",
                "Devonport (C)",
                "Launceston (C)",
                "Glamorgan/Spring Bay (M)",
                "Burnie (C)",
                "Derwent Valley (M)",
                "West Coast (M)",
                "Flinders (M)",
                "Sorell (M)",
                "Central Highlands (M)",
                "Circular Head (M)",
                "Clarence (C)",
                "Northern Midlands (M)",
                "Southern Midlands (M)",
                "Meander Valley (M)",
                "West Tamar (M)",
                "Tasman (M)",
                "Latrobe (M)",
                "Break O'Day (M)",
                "Brighton (M)",
                "Glenorchy (C)",
                "Hobart (C)",
                "Huon Valley (M)",
                "Kingborough (M)",
                "King Island (M)",
                "Kentish (M)",
                "Central Coast (M)",
                "Waratah/Wynyard (M)"
            ],
            "name" : "Tasmania",
            "nrm" : [
                "Marine NRM",
                "North West NRM Region",
                "South NRM Region",
                "North NRM Region"
            ],
            "locality" : "",
            "centre" : [
                "146.59429039923327",
                "-41.93602432206031"
            ],
            "aream2" : 68241834215.61387,
            "pid" : "3742610",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Tasmania (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Tasmanian Central Highlands",
                "Tasmanian Southern Ranges",
                "King",
                "Ben Lomond",
                "Tasmanian Northern Slopes",
                "Tasmanian West",
                "Tasmanian South East",
                "Flinders",
                "Tasmanian Northern Midlands"
            ],
            "imcra4_pb" : [
                "Tasmanian Shelf Province",
                "Southeast Shelf Transition",
                "Bass Strait Shelf Province",
                "Western Bass Strait Shelf Transition"
            ],
            "elect" : [
                "CLARK",
                "LYONS",
                "FRANKLIN",
                "BASS",
                "BRADDON"
            ],
            "cmz" : [
                "Tasman temperate forests",
                "Tasman temperate rainforests and highland forests"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "Directory of Important Wetlands",
                "Indigenous Protected Areas 2013"
            ],
            "gerSubRegion" : [ ]
        },
        "source" : "pid"
    },
    "name" : "Tasmania",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};
var waState = {
    "dateCreated" : ISODate("2020-03-12T23:24:22.929Z"),
    "isSciStarter" : false,
    "lastUpdated" : ISODate("2020-03-12T23:25:18.106Z"),
    "siteId" : UUID.generate(),
    "status" : "active",
    "address" : "",
    "nrm" : "",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "state" : "",
    "area" : "",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 2536095.6101805917,
            "lga" : [
                "Morawa (S)",
                "Nungarin (S)",
                "Cranbrook (S)",
                "Esperance (S)",
                "Gnowangerup (S)",
                "Mandurah (C)",
                "Mount Marshall (S)",
                "Mount Magnet (S)",
                "Derby-West Kimberley (S)",
                "York (S)",
                "Northampton (S)",
                "Woodanilling (S)",
                "Denmark (S)",
                "Gingin (S)",
                "Cue (S)",
                "Coolgardie (S)",
                "Katanning (S)",
                "Capel (S)",
                "Dandaragan (S)",
                "Dalwallinu (S)",
                "Dowerin (S)",
                "Bayswater (C)",
                "Broomehill-Tambellup (S)",
                "Corrigin (S)",
                "Northam (S)",
                "Lake Grace (S)",
                "Meekatharra (S)",
                "Laverton (S)",
                "Dardanup (S)",
                "Roebourne (S)",
                "Pingelly (S)",
                "Nedlands (C)",
                "Koorda (S)",
                "Mingenew (S)",
                "Cuballing (S)",
                "Dumbleyung (S)",
                "Dundas (S)",
                "Bruce Rock (S)",
                "Carnarvon (S)",
                "Wickepin (S)",
                "Carnamah (S)",
                "Yilgarn (S)",
                "Coorow (S)",
                "Wiluna (S)",
                "Collie (S)",
                "Serpentine-Jarrahdale (S)",
                "Stirling (C)",
                "Wanneroo (C)",
                "Perth (C)",
                "Wyndham-East Kimberley (S)",
                "Westonia (S)",
                "Armadale (C)",
                "Moora (S)",
                "Harvey (S)",
                "Sandstone (S)",
                "South Perth (C)",
                "Mosman Park (T)",
                "Bunbury (C)",
                "Ngaanyatjarraku (S)",
                "Swan (C)",
                "Williams (S)",
                "Chapman Valley (S)",
                "Chittering (S)",
                "Cockburn (C)",
                "Tammin (S)",
                "Albany (C)",
                "Augusta-Margaret River (S)",
                "Ashburton (S)",
                "Nannup (S)",
                "Narembeen (S)",
                "Perenjori (S)",
                "Peppermint Grove (S)",
                "Port Hedland (T)",
                "Ravensthorpe (S)",
                "Fremantle (C)",
                "Kwinana (T)",
                "Kulin (S)",
                "Wyalkatchem (S)",
                "Rockingham (C)",
                "Shark Bay (S)",
                "Cambridge (T)",
                "Bridgetown-Greenbushes (S)",
                "Waroona (S)",
                "Kondinin (S)",
                "Boddington (S)",
                "Boyup Brook (S)",
                "Canning (C)",
                "Cottesloe (T)",
                "East Pilbara (S)",
                "Jerramungup (S)",
                "Irwin (S)",
                "Kalamunda (S)",
                "Joondalup (C)",
                "Kent (S)",
                "Manjimup (S)",
                "Mullewa (S)",
                "Mundaring (S)",
                "Mukinbudin (S)",
                "Murchison (S)",
                "Bassendean (T)",
                "Belmont (C)",
                "Beverley (S)",
                "Busselton (S)",
                "West Arthur (S)",
                "Three Springs (S)",
                "Toodyay (S)",
                "Kellerberrin (S)",
                "Kojonup (S)",
                "Gosnells (C)",
                "Geraldton-Greenough (C)",
                "Trayning (S)",
                "Exmouth (S)",
                "Donnybrook-Balingup (S)",
                "Wongan-Ballidu (S)",
                "Yalgoo (S)",
                "Narrogin (T)",
                "Plantagenet (S)",
                "Narrogin (S)",
                "Wagin (S)",
                "Claremont (T)",
                "Leonora (S)",
                "Brookton (S)",
                "Kalgoorlie/Boulder (C)",
                "Cunderdin (S)",
                "Halls Creek (S)",
                "Merredin (S)",
                "Melville (C)",
                "Upper Gascoyne (S)",
                "Victoria Park (T)",
                "Vincent (T)",
                "Victoria Plains (S)",
                "Murray (S)",
                "Wandering (S)",
                "East Fremantle (T)",
                "Quairading (S)",
                "Goomalling (S)",
                "Subiaco (C)",
                "Broome (S)",
                "Menzies (S)"
            ],
            "name" : "Western Australia",
            "nrm" : "",
            "locality" : "",
            "centre" : [
                "122.17836792841851",
                "-25.47089157826687"
            ],
            "aream2" : 2534730050974.1016,
            "pid" : "3742607",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Western Australia (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Coolgardie",
                "Mallee",
                "Geraldton Sandplains",
                "Great Sandy Desert",
                "Ord Victoria Plain",
                "Tanami",
                "Dampierland",
                "Central Ranges",
                "Northern Kimberley",
                "Pilbara",
                "Swan Coastal Plain",
                "Gascoyne",
                "Yalgoo",
                "Avon Wheatbelt",
                "Great Victoria Desert",
                "Gibson Desert",
                "Jarrah Forest",
                "Warren",
                "Little Sandy Desert",
                "Esperance Plains",
                "Central Kimberley",
                "Hampton",
                "Murchison",
                "Victoria Bonaparte",
                "Nullarbor",
                "Carnarvon"
            ],
            "imcra4_pb" : [
                "Northwest Transition",
                "Great Australian Bight Shelf Transition",
                "Northwest Shelf Transition",
                "Southwest Shelf Province",
                "Southwest Shelf Transition",
                "Northwest Shelf Province",
                "Central Western Shelf Transition",
                "Central Western Shelf Province",
                "Timor Province"
            ],
            "elect" : [
                "SWAN",
                "CURTIN",
                "STIRLING",
                "COWAN",
                "MOORE",
                "PEARCE",
                "FORREST",
                "O'CONNOR",
                "DURACK",
                "CANNING",
                "BURT",
                "TANGNEY",
                "BRAND",
                "FREMANTLE",
                "HASLUCK",
                "PERTH"
            ],
            "cmz" : [
                "Swan Coastal Plain shrublands and woodlands",
                "North Australian tropical savanna woodlands",
                "Western Australian temperate sandplain woodlands",
                "South Western Australia temperate woodlands",
                "Arid shrublands and desert",
                "Esperance coastal shrublands and mallee",
                "South Western Australia temperate forests",
                "South Western Australia mallee woodlands"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "RAMSAR wetland regions",
                "Directory of Important Wetlands",
                "Exclusive Economic Zone",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements"
            ],
            "gerSubRegion" : [ ]
        },
        "source" : "pid"
    },
    "name" : "Western Australia",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};
var qldState = {
    "dateCreated" : ISODate("2020-03-13T00:19:45.762Z"),
    "isSciStarter" : false,
    "lastUpdated" : ISODate("2020-03-13T00:20:42.461Z"),
    "siteId" : UUID.generate(),
    "status" : "active",
    "address" : "",
    "nrm" : "",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "state" : "",
    "area" : "",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 1738711.1603665466,
            "lga" : [
                "Diamantina (S)",
                "Doomadgee (S)",
                "MacDonnell (S)",
                "Maranoa (R)",
                "Mapoon (S)",
                "Cairns (R)",
                "Lockyer Valley (R)",
                "Winton (S)",
                "Scenic Rim (R)",
                "Hinchinbrook (S)",
                "Gladstone (R)",
                "Torres Strait Island (R)",
                "Northern Peninsula Area (R)",
                "Bulloo (S)",
                "Barcoo (S)",
                "Yarrabah (S)",
                "Cassowary Coast (R)",
                "Somerset (R)",
                "South Burnett (R)",
                "Southern Downs (R)",
                "Wujal Wujal (S)",
                "Logan (C)",
                "McKinlay (S)",
                "Barkly (S)",
                "Cook (S)",
                "Fraser Coast (R)",
                "Carpentaria (S)",
                "Central Highlands (R)",
                "Central Desert (S)",
                "Charters Towers (R)",
                "Cherbourg (S)",
                "Cloncurry (S)",
                "Weipa (T)",
                "Napranum (S)",
                "Whitsunday (R)",
                "North Burnett (R)",
                "Palm Island (S)",
                "Paroo (S)",
                "Pormpuraaw (S)",
                "Redland (C)",
                "Quilpie (S)",
                "Rockhampton (R)",
                "Richmond (S)",
                "Sunshine Coast (R)",
                "Tablelands (R)",
                "Tenterfield (A)",
                "Barcaldine (R)",
                "Kowanyama (S)",
                "Brewarrina (A)",
                "Bourke (A)",
                "Croydon (S)",
                "Brisbane (C)",
                "Etheridge (S)",
                "Goondiwindi (R)",
                "Gold Coast (C)",
                "Hope Vale (S)",
                "Inverell (A)",
                "Isaac (R)",
                "Ipswich (C)",
                "Mackay (R)",
                "Boulia (S)",
                "Toowoomba (R)",
                "Roper Gulf (S)",
                "Woorabinda (S)",
                "Gympie (R)",
                "Flinders (S)",
                "Torres (S)",
                "Murweh (S)",
                "Mount Isa (C)",
                "Lockhart River (S)",
                "Longreach (R)",
                "Moreton Bay (R)",
                "Moree Plains (A)",
                "Kyogle (A)",
                "Townsville (C)",
                "Tweed (A)",
                "Unincorporated SA",
                "Unincorporated NSW",
                "Walgett (A)",
                "Balonne (S)",
                "Aurukun (S)",
                "Banana (S)",
                "Burdekin (S)",
                "Western Downs (R)",
                "Burke (S)",
                "Bundaberg (R)",
                "Blackall Tambo (R)",
                "Mornington (S)"
            ],
            "name" : "Queensland",
            "nrm" : "",
            "locality" : "",
            "centre" : [
                "144.54503858938244",
                "-22.568753631708326"
            ],
            "aream2" : 1738222385659.9414,
            "pid" : "3742606",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Northern Territory (including Coastal Waters)",
                "New South Wales (including Coastal Waters)",
                "South Australia (including Coastal Waters)",
                "Queensland (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Mulga Lands",
                "Nandewar",
                "Central Mackay Coast",
                "Gulf Fall and Uplands",
                "Mitchell Grass Downs",
                "Brigalow Belt South",
                "Simpson Strzelecki Dunefields",
                "Brigalow Belt North",
                "Cape York Peninsula",
                "Mount Isa Inlier",
                "Gulf Plains",
                "New England Tablelands",
                "NSW North Coast",
                "Einasleigh Uplands",
                "Darling Riverine Plains",
                "Channel Country",
                "Wet Tropics",
                "South Eastern Queensland",
                "Desert Uplands"
            ],
            "imcra4_pb" : [
                "Northeast Shelf Province",
                "Cape Province",
                "Northern Shelf Province",
                "Northeast Shelf Transition",
                "Northeast Province",
                "Central Eastern Shelf Transition"
            ],
            "elect" : [
                "MCPHERSON",
                "MONCRIEFF",
                "RANKIN",
                "MORETON",
                "OXLEY",
                "BOWMAN",
                "GRIFFITH",
                "FADDEN",
                "GROOM",
                "LONGMAN",
                "FAIRFAX",
                "GREY",
                "FISHER",
                "MARANOA",
                "HINKLER",
                "WIDE BAY",
                "FLYNN",
                "HERBERT",
                "KENNEDY",
                "DAWSON",
                "PARKES",
                "NEW ENGLAND",
                "PAGE",
                "RICHMOND",
                "BRISBANE",
                "FORDE",
                "WRIGHT",
                "RYAN",
                "LEICHHARDT",
                "CAPRICORNIA",
                "LINGIARI",
                "LILLEY",
                "PETRIE",
                "DICKSON",
                "BLAIR",
                "BONNER"
            ],
            "cmz" : [
                "Eastern Australia mulga shrublands",
                "Brigalow woodlands",
                "Eastern Australia tropical rainforests",
                "Eastern Australia woodlands",
                "Eastern Australia temperate and subtropical forests",
                "Mitchell grasslands",
                "North Australian tropical savanna woodlands",
                "Arid shrublands and desert",
                "North Eastern Australia tropical rainforests"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "RAMSAR wetland regions",
                "Directory of Important Wetlands",
                "NSW Local Land Services Regions",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Great Eastern Ranges Initiative",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements",
                "Areas for Further Assessment within the East Marine Region"
            ],
            "gerSubRegion" : [
                "GER Border Ranges"
            ]
        },
        "source" : "pid"
    },
    "name" : "Queensland",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};

var vicState = {
    "dateCreated" : ISODate("2020-03-13T00:23:27.714Z"),
    "isSciStarter" : false,
    "lastUpdated" : ISODate("2020-03-13T00:23:43.903Z"),
    "siteId" : UUID.generate(),
    "status" : "active",
    "address" : "",
    "nrm" : "",
    "externalId" : "",
    "poi" : [ ],
    "context" : "none",
    "state" : "",
    "area" : "",
    "description" : "",
    "extent" : {
        "geometry" : {
            "fid" : "cl22",
            "area" : 227711.74073643668,
            "lga" : [
                "Wellington (S)",
                "Corowa Shire (A)",
                "Corangamite (S)",
                "Murray (A)",
                "East Gippsland (S)",
                "Knox (C)",
                "Manningham (C)",
                "Maroondah (C)",
                "Maribyrnong (C)",
                "Stonnington (C)",
                "Queenscliffe (B)",
                "Macedon Ranges (S)",
                "Indigo (S)",
                "Mornington Peninsula (S)",
                "Wyndham (C)",
                "Wentworth (A)",
                "Campaspe (S)",
                "Monash (C)",
                "Hobsons Bay (C)",
                "Melton (S)",
                "Hepburn (S)",
                "Bayside (C)",
                "Mount Alexander (S)",
                "Alpine (S)",
                "Wodonga (RC)",
                "Greater Geelong (C)",
                "Greater Hume Shire (A)",
                "Hume (C)",
                "Casey (C)",
                "Southern Mallee (DC)",
                "Cardinia (S)",
                "Flinders (M)",
                "Loddon (S)",
                "Horsham (RC)",
                "Glenelg (S)",
                "Yarra (C)",
                "Yarra Ranges (S)",
                "Central Goldfields (S)",
                "Yarriambiack (S)",
                "Colac-Otway (S)",
                "Tatiara (DC)",
                "Ararat (RC)",
                "Warrnambool (C)",
                "Naracoorte and Lucindale (DC)",
                "Whittlesea (C)",
                "Nillumbik (S)",
                "Whitehorse (C)",
                "Northern Grampians (S)",
                "Pyrenees (S)",
                "Port Phillip (C)",
                "Renmark Paringa (DC)",
                "Darebin (C)",
                "Frankston (C)",
                "Southern Grampians (S)",
                "Mansfield (S)",
                "Golden Plains (S)",
                "Strathbogie (S)",
                "Surf Coast (S)",
                "Swan Hill (RC)",
                "Baw Baw (S)",
                "Banyule (C)",
                "Bass Coast (S)",
                "Berrigan (A)",
                "Albury (C)",
                "Moonee Valley (C)",
                "Latrobe (C)",
                "Brimbank (C)",
                "Glen Eira (C)",
                "Greater Bendigo (C)",
                "Hindmarsh (S)",
                "Loxton Waikerie (DC)",
                "Buloke (S)",
                "Bega Valley (A)",
                "Melbourne (C)",
                "Kingston (C)",
                "Benalla (RC)",
                "West Wimmera (S)",
                "Moyne (S)",
                "South Gippsland (S)",
                "Greater Dandenong (C)",
                "Grant (DC)",
                "Murrindindi (S)",
                "Greater Shepparton (C)",
                "Mitchell (S)",
                "Moira (S)",
                "Mildura (RC)",
                "Moorabool (S)",
                "Gannawarra (S)",
                "Moreland (C)",
                "Tumbarumba (A)",
                "Towong (S)",
                "Unincorporated SA",
                "Unincorporated Vic",
                "Wakool (A)",
                "Wangaratta (RC)",
                "Balranald (A)",
                "Ballarat (C)",
                "Wattle Range (DC)",
                "Boroondara (C)"
            ],
            "name" : "Victoria",
            "nrm" : [
                "Wimmera",
                "Western",
                "West Gippsland",
                "South East NSW",
                "North East",
                "South East",
                "South Australian Murray Darling Basin",
                "Port Phillip and Western Port",
                "North Central",
                "North NRM Region",
                "Murray",
                "Mallee",
                "Goulburn Broken",
                "Glenelg Hopkins",
                "East Gippsland",
                "Corangamite"
            ],
            "locality" : "",
            "centre" : [
                "144.29908119594236",
                "-36.84968275012256"
            ],
            "aream2" : 227655936548.42267,
            "pid" : "3742609",
            "layerName" : "Australian States and Territories",
            "state" : [
                "Tasmania (including Coastal Waters)",
                "New South Wales (including Coastal Waters)",
                "South Australia (including Coastal Waters)",
                "Victoria (including Coastal Waters)"
            ],
            "type" : "pid",
            "ibra" : [
                "Riverina",
                "Australian Alps",
                "South Eastern Highlands",
                "South East Corner",
                "Murray Darling Depression",
                "Naracoorte Coastal Plain",
                "Victorian Volcanic Plain",
                "Victorian Midlands",
                "NSW South Western Slopes",
                "Flinders",
                "South East Coastal Plain"
            ],
            "imcra4_pb" : [
                "Southeast Shelf Transition",
                "Bass Strait Shelf Province",
                "Western Bass Strait Shelf Transition"
            ],
            "elect" : [
                "MONASH",
                "HOLT",
                "DUNKLEY",
                "LA TROBE",
                "ISAACS",
                "CORIO",
                "MELBOURNE",
                "MENZIES",
                "COOPER",
                "JAGAJAGA",
                "SCULLIN",
                "WILLS",
                "MARIBYRNONG",
                "FRASER",
                "GORTON",
                "CALWELL",
                "BALLARAT",
                "MCEWEN",
                "INDI",
                "BENDIGO",
                "NICHOLLS",
                "KOOYONG",
                "CORANGAMITE",
                "WANNON",
                "MALLEE",
                "LALOR",
                "MACNAMARA",
                "GELLIBRAND",
                "FLINDERS",
                "BASS",
                "BRUCE",
                "FARRER",
                "GOLDSTEIN",
                "ASTON",
                "HOTHAM",
                "CASEY",
                "EDEN-MONARO",
                "CHISHOLM",
                "HIGGINS",
                "DEAKIN",
                "BARKER",
                "GIPPSLAND"
            ],
            "cmz" : [
                "Naracoorte woodlands",
                "Tasman temperate forests",
                "South Eastern Australia mallee woodlands",
                "South Eastern Australia mixed temperate forests woodlands and grasslands",
                "South Eastern Australia temperate woodlands",
                "Australian Alps montane grasslands and heathlands"
            ],
            "other" : [
                "Australian Coral Ecoregions",
                "RAMSAR wetland regions",
                "Directory of Important Wetlands",
                "NSW Local Land Services Regions",
                "National Native Title Register (NNTR, Determinations of Native Title) - boundaries and core attributes",
                "Atlas of Life in the Coastal Wilderness",
                "Great Eastern Ranges Initiative",
                "Indigenous Protected Areas 2013",
                "Indigenous Land Use Agreements"
            ],
            "gerSubRegion" : [
                "GER Central Victorial Biolinks",
                "GER Kosciuszko to Coast",
                "GER Slopes To Summit",
                "GER Victorian BioLinks"
            ]
        },
        "source" : "pid"
    },
    "name" : "Victoria",
    "notes" : "",
    "type" : "managementUnitArea",
    "visibility" : "private"
};

var stateLists = [nswSite, tasState, saState, qldState, waState, vicState];
for (var i = 0; i<stateLists.length; i++){
    var stateSearchResult = db.site.find({name:stateLists[i].name, type:stateLists[i].type});
    if (!stateSearchResult.hasNext()){
        db.site.insert(stateLists[i]);
        print("Site Name: "+ stateLists[i].name + "inserted")

    }
    else {
        print("Search for "+stateLists[i].name +" returned "+stateSearchResult.count()+ " results, not inserting")
    }
}

var actMu = db.managementUnit.find({name:"ACT"}).next();
var actStateSiteId = actMu.managementUnitSiteId;
var ntMu = db.managementUnit.find({name:"Northern Territory"}).next();
var ntStateSiteId = ntMu.managementUnitSiteId;

var states = [
    {
        name: "New South Wales Bushfires",
        acronym: "NSW",
        siteId: nswSite.siteId
    },
    {
        name:"South Australia Bushfires",
        acronym: "SA",
        siteId: saState.siteId
    },
    {
        name:"Tasmania Bushfires",
        acronym:"TAS",
        siteId:tasState.siteId
    },
    {
        name:"Queensland Bushfires",
        acronym:"QLD",
        siteId:qldState.siteId
    },
    {
        name:"Western Australia Bushfires",
        acronym:"WA",
        siteId:waState.siteId
    },
    {
        name:"Victoria Bushfires",
        acronym:"VIC",
        siteId:vicState.siteId
    },
    {
        name:"ACT Bushfires",
        acronym:"ACT",
        siteId:actStateSiteId
    },
    {
        name:"Northern Territory Bushfires",
        acronym:"NT",
        siteId:ntStateSiteId
    },

];
for (var i=0; i<states.length; i++) {
    var state = states[i];

    var mu = {
        name:state.name,
        acronym:state.acronym,
        managementUnitId:UUID.generate(),
        dateCreated:now,
        dateUpdated:now,
        config:{},
        status:'active',
        managementUnitSiteId: state.siteId
    };

    var existingMU = db.managementUnit.find({name:states[i].name});
    if (!existingMU.hasNext()) {
        db.managementUnit.insert(mu);
        print(mu.name+" "+mu.managementUnitId);
    }
}