load("uuid.js");

function createBushFireManagementUnit(states){
    var now = ISODate();
    for (var i=0; i<states.length; i++) {
        var state = states[i];

        var mu = {
            name:state.name,
            managementUnitId:UUID.generate(),
            dateCreated:now,
            dateUpdated:now,
            config:{},
            priorities: [],
            status:'active'
        };

        var existingMU = db.managementUnit.find({name:states[i].name});
        if (!existingMU.hasNext()) {
            db.managementUnit.insert(mu);
            print(mu.name+" "+mu.managementUnitId);
        }
    }
}

function updateSpecies (ts, mgUnit, category){
    var management = db.managementUnit.find({name: mgUnit});
    while (management.hasNext()) {
        var m = management.next();
        ts.forEach(function (species) {
            var isPrioritiesExist = false;
                for (i = 0; i < m.priorities.length; i++) {
                    if (m.priorities[i].category === category && m.priorities[i].priority === species) {
                        isPrioritiesExist = true
                    }
                }
                if (!isPrioritiesExist) {
                    m.priorities.push({category: category, priority: species});
                    print("Saving this " + species + " to the mangement unit: " + m.name + " under this category: " + category)
                    db.managementUnit.save(m);
                }

        });
    }

}

function removePrioritiesIfpresent(options){
    var {mgUnit, management, category} = options
    mgUnit.priorities.forEach(function(priorities){
        if (priorities.category === category){
            print("Removing Existing other species")
            print("ManagementUnit: " + management + " Category: " + priorities.category  + " species: " + priorities.priority)
            db.managementUnit.update({managementUnitId: mgUnit.managementUnitId},{"$pull": { "priorities": {"category":category}}},{"multi": true});
        }
    });

}

function addTsToMus(managementUnit, ts, category) {
    if (!category) {
        category = 'Threatened Species';
    }
    managementUnit.forEach(function (management) {
        var muExist = db.managementUnit.find({name: management});
        while (muExist.hasNext()) {
            var mgUnit = muExist.next();
            if (mgUnit.priorities.length > 0){
                var options = {mgUnit, management, category}
                removePrioritiesIfpresent(options);
            }
            print("Adding species after removing species from the priorities list")
            updateSpecies(ts, management, category)
       }
   });
}
var states = [
    {
        name: "Alpine Bushfire"
    },
    {
        name: "Greater Blue Mountains Bushfire"

    },
    {
        name: "East Gippsland Bushfire"
    },
    {
        name: "Kangaroo Island Bushfire"
    },
    {
        name: "NSW North Coast And Tablelands Bushfire"
    },
    {
        name: "NSW South Coast Bushfire"
    },
    {
        name: "South-East Queensland Bushfire"
    }
    ]
createBushFireManagementUnit(states)
var alpineTEC = [
"Alpine Sphagnum Bogs and Associated Fens",
"Ecological vegetation classes (EVC) dominated by fire sensitive eucalypt species",
"Ecological vegetation classes dominated by callitris pine",
"Montane Peatlands and Swamps of the New England Tableland, NSW North Coast, Sydney Basin, South East Corner, South Eastern Highlands and Australian Alps bioregions",
"Podocarpus heathland",
"Kosciuszko-Namadgi Alpine Ash Moist Grassy Forest",
"Jounama Snow Gum Shrub Woodland",
"Alpine Snow Gum Woodland",
"Black Sallee Woodland",
"White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland",
"Natural Temperate Grassland of the South Eastern Highlands",
"Alpine Teatree shrubland",
"Kosciuszko Flanks Moist Gully Forest",
"Kosciuszko Snow Gum-Mountain Gum Moist Forest",
"Kosciuszko-Namadgi Alpine Ash Moist Grassy Forest",
"Jounama Snow Gum Shrub Woodland",
"Kosciuszko Western Flanks Moist Shrub Forest",
"Kosciuszko Eastern Slopes Mountain Gum Forest",
"Namadgi Subalpine Rocky Shrubland",
"Kybeyan Montane Heath",
"Eucalyptus niphophila woodlands (Alpine Snow Gum Woodland)"
];
var alpineSpecies = [
"Mountain Pygmy-possum (Burramys parvus)",
"Alpine She-oak Skink",
"Northern Corroboree Frog",
"Southern Corroboree Frog",
"Spotted Tree Frog",
"Long-footed Potoroo (Potorous longipes)",
"Dusky Antechinus (Antechinus mimetes)",
"Platypus (Ornithorhynchus anatinus)",
"Koala (Phascolarctos cinereus)",
"Long-nosed Potoroo (Potorous tridactylus)",
"New Holland Mouse, Pookila (Pseudomys novaehollandiae)",
"Brush-tailed Rock-wallaby (Petrogale penicillata)",
"Grey-headed Flying-fox (Pteropus poliocephalus)",
"Superb Lyrebird (Menura novaehollandiae)",
"Gang-gang Cockatoo (Callocephalon fimbriatum)",
"Pilotbird (Pycnoptilus floccosus)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Regent Honeyeater (Anthochaera phrygia)",
"Black-faced Monarch (Monarcha melanopsis)",
"Glossy Black-Cockatoo (eastern) (Calyptorhynchs lathami)",
"Flathead Galaxias, Beaked Minnow, Dargo Galaxias (Galaxias rostratus)",
"Alpine She-oak Skink (Cyclodomorphs praealtus)",
"Alpine Bog Skink (Pseudemoia cryodroma)",
"Guthega Skink (Liopholis guthega)",
"Glossy Grass Skink, Swampland Cool-skink (Pseudemoia rawlinsoni)",
"Southern Water-skink (Eulamprus typmanum)",
"Southern Corroboree Frog (Pseudophryne corroboree)",
"Spotted Tree Frog (Litoria spenceri)",
"Northern Corroboree Frog (Pseudophryne pengilleyi)",
"Spot-tailed Quoll (Dasyurus maculatus)",
"Broad-toothed Rat (Mastacomys fuscus mordicus)",
"Eastern Bentwing Bat (Miniopterus orianae oceanensis)",
"Yellow-bellied Glider (Petaurus australis)",
"Squirrel Glider (Petaurus norfolcensis)",
"Southern Greater Glider (Petauroides volans)",
"Long-footed Potoroo (Potorous longipes)",
"Smoky Mouse (Pseudomys fumeus)",
"Sloanes Froglet (Crinia sloanei)",
"Booroolong Tree Frog (Litoria booroolongensis)",
"Alpine Tree Frog (Litoria verreauxii alpina)",
"Macquarie Perch (Macquaria australasica)",
"Stocky Galaxias (Galaxias tantangara)",
"Two-spined Blackfish (Gadopsis bispinosus)",
"Gang gang Cockatoo (Callocephalon fimbriatum)",
"Brown Treecreeper (Climacteris picumnus victoriae)",
"Black-chinned Honeyeater (Melithreptus gularis)",
"Turquoise Parrot (Neophema pulchella)",
"Barking Owl (Ninox connivens)",
"Powerful Owl (Ninox strenua)",
"Diamond Firetail (Stagonopleura guttata)",,
"Alpine Silver (Xenica Oreixenica lathalis theddora)",
"Yarrangobilly Pinwheel Snail (Hedleyropa yarrangobillyensis)",
"leaf beetle (Buburra jeanae)",
"harpactacoid copepod (Canthocamptus longipes)",
"Alpine crayfish (Euastacus crassus.)",
"Orbost Spiny Crayfish (Euastacus diversus)",
"Riek's Crayfish (Euastacus rieki)",
"Alpine Stonefly (Thaumatoperia alpina)",
"jewel beetle (Castiarina flavoviridis)",
"Koscuiszko Bristle Snail (Austrochloritis kosciuszkoensis)",
"Koscuiszko Carnivorous Snail (Austrorhytida glaciamans)",
"Lakes Entrance Pinwheel Snail (Diphyoropa illustra)",
"Small Alpine Xenica (Oreixenica latialis)",
"Alpine Darner (Austroaeschna flavomaculata)",
"Prickle Pinhead Snail (Paralaoma annabelli)",
"Spotted Alpine Xenica (Oreixenica orichora)",
"jewel beetle (Castiarina kershawi)",
"Orange Alpine Xenica; Correa Brown (Oreixenica correae)",
"Beetle (Aulacopris reichei)",
"jewel beetle (Temognatha grandis)",
"Mount Kosciusko Wingless Stonefly (Leptoperla cacuminis)",
"Spider, harvestman or pseudoscorpion (Asteron grayi)",
"Spider, harvestman or pseudoscorpion (Molycria mammosa)",
"Spider, harvestman or pseudoscorpion (Storenosoma terraneum)",
"Thylacine Darner (Acanthaeschna victoria)",
"Waterfall Redspot (Austropetalia patricia)",
"Pine Mountain Grevillea (Grevillea jephcottii)",
"(Grevillea oxyantha subsp. ecarinata)",
"(Olearia stenophylla)",
"Bago Leek-orchid (Prasophyllum bagoense)",
"Brumby Sallee (Eucalyptus forresterae)",
"(Pomaderris helianthemifolia)",
"Kelton’s Leek-orchid (Prasophyllum keltonii)",
"Blue-tongue Greenhood (Pterostylis oreophila)",
"(Gentianella sylvicola)",
"(Pultenaea vrolandii)",
"Lemon-scented Zieria (Zieria citriodora)",
"Leafless Pinkbells (Tetratheca subaphylla)",
"Dainty Bitter-cress (Cardamine tryssa)",
"Blotchy Mintbush (Prostanthera walteri)",
"(Galium roddii)",
"Kydra Dampiera (Dampiera fusca)",
"(Prostanthera stenophylla)",
"(Philotheca myoporoides subsp. brevipedunculata)",
"Dwarf Bottlebrush (Callistemon subulatus)",
"(Dillwynia brunioides)",
"White Mountain Ash, White Ash (Eucalyptus fraxinoides)",
"Nunniong Gum (Eucalyptus elaeophloia)",
"Jervis Bay Grevillea (Grevillea macleayana)",
"(Deyeuxia talariata)",
"Blay’s Wattle (Acacia blayana)",
"(Acacia covenyi)",
"(Acacia mabellae)",
"Mount Buffalo Wattle (Acacia phlebophylla)",
"Phantom Wattle (Acacia phasmoides)",
"(Acacia saliciformis)",
"(Acacia trachyphloia)",
"Slender Parrot Pea (Almalea capitata)",
"Mountain Banksia (Banksia canei)",
"Moonwort (Botrychium lunaria)",
"Mountain Spider Orchid (Caladenia montana)",
"Brownish Beard Orchid (Calochilus sandrae)",
"Leafless Beard Orchid (Calochilus saprophyticus)",
"(Cassinia heleniae)",
"(Cassinia venusta)",
"(Cassytha phaeolasia)",
"A snow daisy (Celmisia sp pulchella)",
"Kydra Dampiera (Dampiera fusca)",
"(Daviesia nova-anglica)",
"(Deyeuxia reflexa)",
"(Dillwynia palustris)",
"Leafy Anchor Plant (Discaria nitida)",
"Pale Golden Moths (Diuris ochroma)",
"(Eucalyptus cinerea subsp. triplex)",
"(Eucalyptus forresterae)",
"(Eucalyptus forresterae)",
"Rough Eyebright (Euphrasia scabra)",
"(Galium roddii)",
"East Lynne Midge Orchid (Genoplesium vernale)",
"Baeuerlen's Gentian (Gentiana baeuerlenii)",
"Mueller’s Snow-gentian (Gentianella muelleriana subsp. jingerensis)",
"(Geranium sessiliflorum)",
"(Goodenia glomerata)",
"(Grevillea imberbis)",
"Buffalo Grevillea (Grevillea alpivaga)",
"(Grevillea macleayana)",
"(Grevillea neurophylla subsp fluviatilis)",
"(Grevillea neurophylla subsp neurophylla)",
"(Grevillea oxyantha subsp. ecarinata)",
"Fan Grevillea (Grevillea ramosissima subsp hypargyrea)",
"(Grevillea victoriae subsp nivalis)",
"(Grevillea victoriae subsp nivalis)",
"Omeo Grevillea (Grevillea willisii)",
"(Hakea macraeana)",
"Shiny Phebalium (Leionema lamprophyllum subsp obovatum)",
"Namadgi Tea Tree (Leptospermum namadgiensis)",
"Mountain Logania (Logania granitica)",
"Hoary Sunray (Leucochrysum albicans var. tricolor)",
"Snow Pratia (Lobelia gelida)",
"(Olearia sp Rhizomatica)",
"(Olearia stenophylla)",
"(Parantennaria uniceps)",
"(Persoonia chamaepitys)",
"(Persoonia mollis subsp. mollis)",
"(Persoonia procumbens)",
"(Pimelea bracteata)",
"Cotoneaster Pomaderris (Pomaderris cotoneaster)",
"Grey Deua Pomaderris (Pomaderris gilmourii)",
"(Pomaderris phylicifolia subsp. phylicifolia)",
"Buffalo Mint Bush (Prostanthera monticola)",
"Summer Leek Orchid (Prasophyllum canaliculatum)",
"Brandy Marys leek orchid (Prasophyllum innubum)",
"Kelton's Leek Orchid (Prasophyllum keltonii)",
"Charming Leek Orchid (Prasophyllum venustum)",
"Stocky Leek Orchid (Prasophyllum viriosum)",
"(Prostanthera decussata)",
"(Prostanthera stenophylla)",
"(Prostanthera walteri)",
"Blue-tongued Greenhood / Kiandra Greenhood (Pterostylis oreophila)",
"Dusky Bush-pea (Pultenaea polifolia)",
"Cupped Bush-pea (Pultenaea vrolandii)",
"Monaro Golden Daisy (Rutidosis leiolepis)",
"Fern-leaf Baeckea (Sannantha crenulate)",
"(Tetratheca subaphylla)",
"Austral Toadflax (Thesium austral)",
"Elbow Orchid (Thynninorchis huntianus)",
"Dwarf Violet (Viola improcera)"
];
var greaterTEC = ["Greater Blue Mountains World Heritage Area", "Gondwana Rainforests of Australia World Heritage Area","Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion", "Temperate Highland Peat Swamps on Sandstone", "Lowland Rainforest of Subtropical Australia", "Coastal Swamp Oak (Casuarina glauca) Forest of New South Wales and South East Queensland", "Montane Peatlands and Swamps of the New England Tableland, NSW North Coast, Sydney Basin, South East Corner, South Eastern Highlands and Australian Alps bioregion", "Kurri Sand Swamp Woodland in the Sydney Basin Bioregion", "Lower Hunter Spotted Gum Ironbark Forest in the Sydney Basin and NSW North Coast Bioregions", "Turpentine-Ironbark Forest of the Sydney Basin Bioregion", "Littoral Rainforest and Coastal Vine Thickets of Eastern Australia", "Castlereagh Scribbly Gum and Agnes Banks Woodlands of the Sydney Basin Bioregion"];
var greaterSpecies = [
"Blue Mountains Water Skink (Eulamprus leuraensis)",
"Broad-headed Snake (Hoplocephalus bungaroides)",
"Southern Leaf-Tailed Gecko, Broad-tailed Gecko (Phyllurus platurus)",
"Rockwarbler (Origma solitaria)",
"Brush-tailed rock-wallaby (Petrogale penicillata)",
"Greater glider (Petauroides volans)",
"Yellow-bellied glider (Petaurus australis)",
"Koala (Phascolarctos cinereus)",
"Spotted-tail quoll (Dasyurus maculatus maculatus)",
"Grey-headed flying-fox (Pteropus poliocephalus)",
"Platypus (Ornithorinchus anatinus)",
"Regent Honeyeater (Anthochaera phrygia)",
"Gang-gang Cockatoo (Callocephalon fimbriatum)",
"South-eastern Glossy Black-cockatoo (Calyptorhynchus lathami lathami)",
"Stuttering Frog (Mixophyes balbus)",
"Giant Barred Frog (Mixophyes iteratu)",
"Eastern Bristlebird (Dasyornis brachypterus)",
"Rufous Scrub-bird (Atrichornis rufescens)",
"Parma Wallaby (Notomacropus parma)",
"Hastings River Mouse (Pseudomys oralis)",
"Mustard-bellied Snake (Drysdalia rhodogaster)",
"Red-tailed Calyptotis (Calyptotis ruficauda)",
"Moritz’s leaf-tail gecko (Saltuarius moritzi)",
"Dusky Antechinus (Antechinus mimetes)",
"Golden-tipped Bat (Phoniscus papuensis)",
"Hastings River Mouse, Koontoo (Pseudomys oralis)",
"Littlejohn's Tree Frog, Heath Frog (Litoria littlejohni)",
"Giant Burrowing Frog (Heleioporus australiacus)",
"Stuttering Frog, Southern Barred Frog (Mixophyes balbus)",
"Sphagnum Frog (Philoria sphagnicola)",
"Davies’ Tree Frog (Litoria daviesae)",
"Giant Barred Frog (Mixophyes iteratus)",
"Macquarie Perch (Macquaria australasica 'MDB taxa')",
"Blue Mountains Perch, Hawkesbury Perch (Macquarie sp. nov. 'Hawkesbury taxon')",
"Pilotbird (Pycnoptilus floccosus)",
"Superb Lyrebird (Menura novaehollandiae)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Rufous Scrub-bird (Atrichornis rufescens)",
"Black-faced Monarch (Monarcha melanopsis)",
"Eastern Bristlebird (Dasyornis brachypterus)",
"Mainland Ground Parrot (Pezoporus wallicus wallicus)",
"Blue Mountains Perch",
"Giant Burrowing Frog",
"Red-crowned Toadlet",
"Little Bent-winged Bat",
"Barking Owl",
"Masked Owl",
"Powerful Owl",
"Sooty Owl",
"Manning River Helmeted Turtle, Purvis' Turtle (Myuchelys purvisi)",
"Broad-toothed Rat (Mastacomys fuscus mordicus)",
"Long-nosed Potoroo (Potorous tridactylus tridactylus)",
"New Holland Mouse Pookila (Pseudomys novaehollandiae)",
"Fly (Pelecorhynchus niger)",
"Jewel Beetle",
"Coricudgy Pinwheel Snail (Coricudgia wollemiana)",
"Wolllemi Pinwheel Snail (Macrophallikoropa stenoumbilicata)",
"Fly (Pelecorhynchus nebulosus)",
"Beetle (Matthewsius rossi)",
"Jenolan Pinwheel Snail (Marilyniropa jenolanensis)",
"Jenolan Caves Woodland Snail (Pommerhelix depressa)",
"Wollemi Bristle Snail (Austrochloritis wollemiensis)",
"Beetle (Figulus trilobus)",
"Fly (Pelecorhynchus lineatus)",
"Giant Dragonfly (Petalura gigantea)",
"Bathurst Copper Butterfly (Paralucia spinifera)",
"Sutton’s Crayfish (Euastacus suttoni)",
"Small Crayfish (Euastacus spinichelatus)",
"Many Bristled Crayfish (Euastacus polysetosus)",
"Hanging Rock Crayfish (Euastacus gamilaroi)",
"Blue Mountains Woodland Snail (Pommerhelix monacha)",
"Jenolan Caves Bristle Snail (Austrochloritis kanangra)",
"Montane Iris-skipper; Aeluropis Skipper (Mesodina aeluropis)",
"Green Carpenter Bee, Metallic Green Carpenter Bee, Southern Green Carpenter Bee (Xylocopa aeratus)",
"Prickle Pinhead Snail (Paralaoma annabelli)",
"Beetle (Matthewsius illawarrensis)",
"Spider, harvestman or pseudoscorpion (Storenosoma terraneum)",
"Spider, harvestman or pseudoscorpion (Molycria mammosa)",
"Waterfall Redspot (Austropetalia patricia)",
"Beetle (Aulacopris reichei)",
"Beetle (Diorygopyx incrassatus)",
"Beetle (Coripera morleyana)",
"Depressed Mussel; Knife-shaped Mussel (Hyridella depressa)",
"Fly (Pelecorhynchus distinctus)",
"Small Alpine Xenica (Oreixenica latialis latialis)",
"Spider, harvestman or pseudoscorpion (Venatrix australiensis)",
"Spider, harvestman or pseudoscorpion (Asteron grayi)",
"Wauchope Pinwheel Snail (Gyrocochlea wauchope)",
"Ant, wasp or bee (Tetramorium confusum)",
"Clubbed Shutwing (Cordulephya divergens)",
"Dingy Darter, Sedge Darter, Southern Sedge Darter (Telicota eurychlora)",
"Eastern Freshwater Shrimp (Australatya striolata)",
"Fly (Pelecorhynchus rubidus)",
"Fly (Trichophthalma bivitta)",
"Glistening Pencil-blue; Common Pencilled-blue (Candalides absimilis edwardsi)",
"Jervis Bay Forest Snail (Meridolum jervisensis)",
"Jewel Beetle",
"Large Riverdamsel (Caliagrion billinghursti)",
"Macleay Valley Droplet-snail (Pleuropoma jana)",
"Mount Seaview Pinwheel Snail (Elsothera kyliestumkatae)",
"Orange Alpine Xenica; Correa Brown (Oreixenica correae)",
"Port Stephens Pinwheel Snail (Gyrocochlea planorbis)",
"Spider, harvestman or pseudoscorpion (Graycassis bruxner)",
"Water Flea (Rhynchochydorus australiensis)",
"Hemiptera (bug) (Kirkaldyella rugosa)",
"(Hibbertia cistiflora subsp. quadristaminea)",
"(Persoonia hindii)",
"(Persoonia recedens)",
"(Leucochrysum graminifolium)",
"Benson’s Stringybark (Eucalyptus bensonii)",
"(Leptospermum petraeum,)",
"Kowmung Hakea (Hakea dohertyi)",
"(Almaleea incurvata)",
"Winged Sunshine Wattle (Acacia alaticaulis)",
"(Veronica brownii)",
"(Hibbertia acaulothrix)",
"Olinda Box (Eucalyptus corticosa)",
"(Darwinia taxifolia subsp. taxifolia)",
"(Dillwynia stipulifera)",
"(Haloragodendron lucasii)",
"(Persoonia oblongata)",
"(Persoonia mollis subsp. Mollis)",
"(Epacris purpurascens var. onosmiflora)",
"Rudder's Box (Eucalyptus rudderi)",
"Smooth Bush-pea, Swamp Bush-pea (Pultenaea glabra)",
"(Hakea pachyphylla)",
"(Haloragodendron gibsonii)",
"(Leptospermum macrocarpum)",
"Fletcher's Drumsticks (Isopogon fletcheri)",
"Willow Wattle (Acacia saliciformis)",
"(Banksia penicillata)",
"(Baeckea kandos)",
"(Brachyscome brownii)",
"Wollemi Pine (Wollemia nobilis)",
"(Apatophyllum constablei)",
"(Cyphanthera scabrella)",
"Mountain Trachymene (Trachymene scapigera)",
"Cliff Mallee Ash (Eucalyptus cunninghamii)",
"Needle Geebung (Persoonia acerosa)",
"(Ochrosperma oligomerum)",
"(Hakea constablei)",
"(Veronica lithophila)",
"Kowmung Wattle, Kanangra Wattle (Acacia clunies-rossiae)",
"(Leionema lamprophyllum subsp. Orbiculare)",
"Tawny Leekorchid, Slaty Leekorchid (Prasophyllum fuscum)",
"(Hibbertia saligna)",
"(Eucalyptus sp. Howes Swamp Creek)",
"Mueller’s Cypress (Callitris muelleri)",
"(Grevillea kedumbensis)",
"Dwarf Heath Casuarina (Allocasuarina defungens)",
"(Grevillea imberbis)",
"Rufous Pomaderris (Pomaderris brunnea)",
"Wiry Flannel flower (Actinotus forsythii)",
"Wolgan Snow Gum (Eucalyptus gregsoniana)",
"(Hibbertia coloensis)",
"(Spyridium burragorang)",
"Bent Pomaderris (Pomaderris sericea)",
"Evan’s Grevillea (Grevillea evansiana)",
"Deane's Boronia (Boronia deanei)",
"(Prostanthera caerulea)",
"(Leptospermum spectabile)",
"(Grevillea buxifolia subsp. ecorniculata)",
"(Epacris hamiltonii)",
"(Velleia perfoliata)",
"(Solanum armourense)",
"(Prostanthera stenophylla)",
"(Dillwynia brunioides)",
"Hamilton's Wattle (Acacia hamiltoniana)",
"(Goodenia heterophylla subsp. montana)",
"Swamp Banksia (Banksia paludosa subsp. astrolux)",
"(Schoenus evansianus)",
"(Prostanthera saxicola var. montana)",
"(Grevillea aspleniifolia)",
"Superb Midgeorchid (Genoplesium superbum)",
"(Goodenia rostrivalvis)",
"(Olearia covenyi)",
"(Asterolasia rivularis)",
"Bog Grevillea (Grevillea acanthifolia)",
"(Hibbertia circinata)",
"Jones Wattle (Acacia jonesii)",
"(Acacia meiantha)",
"Megalong Valley Bottlebrush (Callistemon megalongensis)",
"(Hymenophyllum pumilum)",
"(Grevillea guthrieana)",
"Olsen’s Wattle (Acacia olsenii)",
"(Zieria caducibracteata)",
"(Macrozamia montana)",
"Three-nerved Wattle (Acacia trinervata)",
"(Deyeuxia reflexa)",
"Camden Woollybutt, Paddys River Box (Eucalyptus macarthurii)",
"Cotoneaster Pomaderris (Pomaderris cotoneaster)",
"Blue Bush, Bluebush, Bendethera Wattle (Acacia covenyi)",
"(Microlaena stipoides var. breviseta)",
"(Acacia tessellata)",
"Monga Waratah, Braidwood Waratah (Telopea mongaensis)",
"(Styphelia perileuca)",
"Chalker's Wattle (Acacia chalkeri)",
"Dwarf Bottlebrush (Callistemon subulatus)",
"(Leptospermum rotundifolium)",
"Linsmith's Grevillea (Grevillea linsmithii)",
"(Lasiopetalum joyceae)",
"(Asterolasia buxifolia)",
"(Grevillea acerata)",
"(Prostanthera teretifolia)",
"Paddys River Box (Eucalytus macarthurii)",
"Wollemi Pine (Wollemia nobilis)",
"Dwarf Mountain Pine (Pherosphaera fitzgeraldii)",
"Coveny’s Zieria (Zieria convenyi)",
"(Leionema lachnaeoides)",
"(Grevillea obtusiflora ssp)",
"Donkey Orchid (Diuris aequalis)",
"(Epacris sparsa)",
"Fletchers Drumsticks (Isopogon fletcheri)",
"(Trachymene saniculifolia)",
"(Bertya sp.)",
"Evans Grevillea (Grevillea evansiana)",
"(Hibbertia puberula)",
"(Hibbertia sp. Bankstown)",
"(Pultenaea sp. Olinda)",
"Rylstone Bell (Leionema sympetalum)",
"(Velleia perfoliata)",
"Velvet Zieria (Zieria murphyi)"
];
var eastGippslandTEC = []
var eastGippslandSpecies = [
"Long-footed potoroo (Potorous longipes)",
"Smoky Mouse, Konoom (Pseudomys fumeus)",
"Long-nosed Potoroo (Potorous tridactylus)",
"Dusky Antechinus (Antechinus mimetes)",
"Broad-toothed Rat (Mastacomys fuscus mordicus)",
"Yellow-bellied Glider (Petaurus australis)",
"Greater Glider (Petauroides volans)",
"Platypus (Ornithorhynchus anatinus)",
"Brush-tailed Rock-wallaby (Petrogale penicillata)",
"Pilotbird (Pycnoptilus floccosus)",
"Superb Lyrebird (Menura novaehollandiae)",
"Eastern bristlebird (Dasyornis brachypterus)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Gang-gang Cockatoo (Callocephalon fimbriatum)",
"Eastern Ground Parrot (Pezoporus wallicus)",
"Regent Honeyeater (Anthochaera phrygia)",
"Gippsland Galaxias (Galaxias aequipinnis)",
"Black-faced Monarch (Monarcha melanopsis)",
"Cann Galaxias (Galaxias species 17 'Cann')",
"McDowall's Galaxias (Galaxias mcdowalli)",
"Yalmy Galaxias (Galaxias sp. nov. 'yalmy')",
"Roundsnout Galaxias (Galaxias terenasus)",
"Dargo Galaxias (Galaxias mungadhan)",
"Non-parasitic Lamprey (Mordacia praecox)",
"Glossy Grass Skink, Swampland Cool-skink",
"Rawlinson’s Window-eyed Skink (Pseudemoia rawlinsoni)",
"Southern Water-skink (Eulamprus tympanum)",
"Alpine Bog Skink, Alpine Bog-skink (Pseudemoia cryodroma)",
"Alpine She-oak Skink (Cyclodomorphus praealtus)",
"Littlejohn’s Tree Frog, Heath Frog (Litoria littlejohni)",
"Giant Burrowing Frog (Heleioporus australiacus)",
"Spotted Tree Frog (Litoria spenceri)",
"Alpine Tree Frog, Verreaux’s Alpine Tree Frog (Litoria verreauxii alpina)",
"Glossy Black-Cockatoo (Calyptorhynchus lathami)",
"Masked Owl (Tyto novaehollandiae)",
"Southern Greater Glider (Petauroides volans)",
"Ground Parrot (Pezoporus wallicus)",
"Large Brown Tree Frog (Litoria littlejohni)",
"Spot-tailed Quoll (Dasyurus maculatus)",
"Giant Burrowing Frog (Heleioporus australiacus)",
"Southern Brown Bandicoot (Isoodon obesulus)",
"Southern Long-nosed Bandicoot (Perameles nasuta)",
"Southern Barred Frog (Mixophyes balbus)",
"Diamond python (Morelia spilota)",
"Australian Grayling (Prototroctes maraena)",
"Macquarie Perch (Macquaria australasica)",
"Arte spiny crayfish (Euastacus sp. 1)",
"Cann spiny crayfish (Euastacus sp. 2)",
"East Gippsland spiny crayfish (Euastacus bidawalus)",
"West Snowy spiny crayfish (Euastacus sp. 3)",
"Orbost spiny crayfish (Euastacus diversus)",
"Sedge darter (Telicota eurychlora)",
"Calyton's Crayfish (Euastacus claytoni)",
"Annabelll's Pinhead Snail, Prickle Pinhead Snail (Paralaoma annabelli)",
"Eastern Freshwater Shrimp (Australatya striolata)",
"a dung beetle (Aulacopris reichei)",
"Kosciuszko Carnivorous Snail (Austrorhytida glaciamans)",
"Waterfall Redspot (Austropetalia patricia)",
"Lakes Entrance Pinwheel Snail (Diphyoropa illustra)",
"Depressed Mussel; Knife-shaped Mussel (Hyridella depressa)",
"Merimbula Woodland Snail (Pommerhelix mastersi)",
"a jewel beetle (Castiarina kershawi)",
"Kosciuszko Bristle Snail (Austrochloritis kosciuszkoensis)",
"Spotted Alpine Xenica (Oreixenica orichora)",
"(Asteron grayi)",
"Alpine Darner (Austroaeschna flavomaculata)",
"(Storenosoma terraneum)",
"Gippsland Banksia (Banksia croajingolensis)",
"Betka Bottlebrush (Callistemon kenmorrisonii)",
"Buchan River Grevillea (Grevillea pachylostyla)",
"(Leptospermum jingera)",
"(Pomaderris buchanensis)",
"Brumby Sallee (Eucalyptus forresterae)",
"Leafy Nematolepis (Nematolepis frondosa)",
"(Leucopogon riparius)",
"(Pomaderris oblongifolia)",
"Forrester's Bottlebrush (Callistemon forresterae)",
"Woolly Wattle, Hairy Wattle (Acacia lanigera var. gracilipes)",
"Snowy River Daisy (Brachyscome riparia)",
"Olive Mallee (Eucalyptus elaeophloia)",
"Brumby Mallee-gum (Eucalyptus phoenix)",
"Tullach Ard Grevillea (Grevillea polychroma)",
"Climbing Bent-grass (Deyeuxia ramosa)",
"(Eucalyptus mackintii)",
"(Olearia rugosa subsp. angustifolia)",
"Smooth Tea-tree (Leptospermum glabrescens)",
"Blotchy Mintbush (Prostanthera walteri)",
"(Monotoca rotundifolia)",
"Bush-pea (Pultenaea parrisiae)",
"(Tetratheca subaphylla)",
"Howe Guinea-flower (Hibbertia notabilis)",
"(Viola improcera)",
"Woolly-bear Wattle, Lucas's Wattle (Acacia lucasii) (Dampiera fusca)",
"Tiny Spyridium (Spyridium cinereum)",
"Mountain Banksia (Banksia canei)",
"Dwarf Bottlebrush (Callistemon subulatus)",
"(Deyeuxia talariata)",
"Harsh Nematolepis (Nematolepis squamea subsp. coriacea)",
"(Grevillea neurophylla)",
"(Grevillea parvula)",
"(Persoonia brevifolia)",
"Narrow-leaf Bower Wattle, Sticky Bower Wattle, River Wattle, Bower Wattle (Acacia subporosa)",
"Wiry Flannel-flower (Actinotus forsythii)",
"Thick-lipped Spider-orchid, Daddy long legs (Caladenia tessellata)",
"White Mountain Ash, White Ash (Eucalyptus fraxinoides)",
"Net-veined Wattle (Acacia subtilinervis)",
"Cotoneaster Pomaderris (Pomaderris cotoneaster)",
"Mignonette Leek-orchid, Cobungra Leek-orchid, Dense Leek-orchid (Prasophyllum morganii)",
"Genoa River Correa (Correa lawrenceana var. genoensis)",
"Leafless Tongue-orchid (Cryptostylis hunteriana)",
"Bent Pomaderris (Pomaderris sericea)",
"Colquhoun Grevillea (Grevillea celata)",
"Rufous Pomaderris (Pomaderris brunnea)",
"Snowy River Westringia (Westringia cremnophila)",
"Limestone Blue Wattle (Acacia caerulescens)",
"Marble Daisy-bush (Olearia astroloba)",
"Narrow-leaf Bent-grass (Deyeuxia pungens)",
"Blue-tongue Greenhood (Pterostylis oreophila)",
"Buff Hazelwood (Symplocos thwaitesii)",
];
var kangarooIslandSpecies = [
"Kangaroo Island dunnart (Sminthopsis griseoventer aitkeni)",
"Kangaroo Island southern emu-wren (Stipiturus malachurus halmaturinus)",
"Glossy black-cockatoo (Kangaroo Island)",
"Glossy black-cockatoo (South Australian) (Calyptorhynchus lathami halmaturinus)",
"Kangaroo Island whipbird (Psophodes nigrogularis lashmari)",
"Kangaroo Island echidna (Tachyglossus aculeatus multiaculeatus)",
"Bassian thrush (South Australian) (Zoothera lunulata halmaturina)",
"Platypus (Ornithorhynchus anatinus)",
"Gang-gang Cockatoo (Callocephalon fimbriatum)",
"Kangaroo Island Micro-trapdoor spider (Moggdridgea rainbowi)",
"Kangaroo Island Assassin spider (Zephyrarchaea austini)",
"Western Kangaroo Island Harvestman (Nunciella kangarooensis)",
"Green Carpenter Bee (Xylocopa aeratus)",
"Large Eastern Bronze Azure Butterfly (Ogyris halmaturia)",
"Small Bronze Azure Butterfly (Ogyris otanes)",
"Kangaroo Island Robust Fan-winged Katydid (Psacadonotus insulanus)",
"Kangaroo Island Marauding Katydid (Metaballus mesopterus)",
"Raspy Cricket (Apteronomus bordaensis / Apteronomus tepperi)",
"Tomsett's Shrubland Snail (Cupedora tomsetti)",
"Cape Borda Corrugated Snail (Glyptorhagada bordaensis)",
"Prickle Pinhead Snail (Paralaoma annabelli)",
"(Abantiades sp. n. Kangaroo Island (per E. Beaver))",
"(Oxycanus sp. n. 'Kartus' (per E. Beaver))",
"Kangaroo Island Ground-berry (Acrotriche halmaturina)",
"Kangaroo Island Gland Flower (Adenanthos macropodianus)",
"Mountain Woodruff (Asperula tetraphylla)",
"(Asterolasia muricata)",
"Kangaroo Island Heath-myrtle (Calytrix smeatoniana)",
"(Cheiranthera volubilis)",
"Kangaroo Island Spiked Sour-bush (Choretrum spicatum)",
"De Mole River Correa (Correa calycina var. halmaturorum)",
"Kangaroo Island Dampiera (Dampiera lanceolata var. insularis)",
"Kangaroo Island Ash (Eucalyptus remota)",
"Kangaroo Island Saw-sedge (Gahnia halmaturina)",
"Kangaroo Island Spiky Saw-sedge (Gahnia hystrix)",
"Small-flower Grevillea (Grevillea halmaturina subsp. halmaturina)",
"Lavender Grevillea (Grevillea lavandulacea subsp. rogersii)",
"Five-veined Grevillea (Grevillea quinquenervis)",
"Enigma Hakea (Hakea aenigma)",
"Scrambling Guinea-flower (Hibbertia empetrifolia subsp. radians)",
"Stalked Guinea-flower (Hibbertia glebosa subsp. oblonga)",
"Robust Guinea-flower (Hibbertia platyphylla subsp. halmaturina)",
"Spreading Pennywort (Hydrocotyle crassiuscula)",
"Kangaroo Island Cress (Irenepharsus phasmatodes)",
"Kangaroo Island Phebalium (Leionema equestre)",
"Kangaroo Island Scale-rush (Lepyrodia valliculae)",
"Kangaroo Island Logania (Logania insularis)",
"Rough Logania (Logania scabrella)",
"Lobed Platysace (Platysace heterophylla var. tepperi)",
"Kangaroo Island Bush-pea (Pultenaea trifida)",
"Tepper's Trigger-plant (Stylidium tepperianum)",
"Curly Pink-bells (Tetratheca halmaturina)",
"Kangaroo Island Pink-eyes (Tetratheca insularis)",
"Pink Zieria (Zieria veronicea subsp. insularis)",
]
var northCoastAndTableLandsTEC = ["Gondwana Rainforests of Australia World Heritage Area", "New England Peppermint (Eucalyptus nova-anglica) Grassy Woodlands", "Lowland Rainforest of Subtropical Australia", "Coastal Swamp Oak (Casuarina glauca) Forest of New South Wales and South East Queensland ecological community"]
var northCoastAndTableLandsSpecies = [
"Hastings River Mouse, Koontoo (Pseudomys oralis)",
"Parma Wallaby (Notamacropus parma)",
"New Holland Mouse, Pookila (Pseudomys novaehollandiae)",
"Brush-tailed Rock-wallaby (Petrogale penicillata)",
"Long-nosed Potoroo (SE Mainland) (Potorous tridactylus tridactylus)",
"Yellow-bellied Glider (Petaurus australis)",
"Spot-tailed Quoll, Spotted-tail Quoll, Tiger Quoll (Dasyurus maculatus maculatus)",
"Greater Glider (Petauroides volans)",
"Koala (Phascolarctos cinereus)",
"Golden-tipped Bat (Phoniscus papuensis)",
"Platypus (Ornithorhynchus anatinus)",
"Rufous Scrub-bird (Atrichornis rufescens)",
"Albert's Lyrebird (Menura alberti)",
"Superb Lyrebird (Menura novaehollandiae)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Glossy Black-Cockatoo (eastern) (Calyptorhynchus lathami lathami)",
"Black-faced Monarch (Monarcha melanopsis)",
"Regent Honeyeater (Anthochaera phrygia)",
"Eastern Ground Parrot (Pezoporus wallicus)",
"Eastern Bristlebird (Dasyornis brachypterus)",
"Kate's Leaf-tail Gecko (Saltuarius kateae)",
"Rainforest Cool-skink (Harrisoniascincus zia)",
"Mortiz’s Leaf-tail gecko (Saltuarius moritzi)",
"Granite Leaf-tailed Gecko (Saltuarius wyberba)",
"Red-tailed Calyptotis (Calyptotis ruficauda)",
"Georges' Snapping Turtle, Bellinger River Snapping Turtle, Georges Helmeted Turtle (Wollumbinia georgesi)",
"Three-toed Snake-tooth Skink (Coeranoscincus reticulatus)",
"Manning River Helmeted Turtle, Purvis' Turtle (Myuchelys purvisi)",
"Bell's Turtle, Western Sawshelled Turtle, Namoi River Turtle, Bell's Saw-shelled Turtle (Wollumbinia belli)",
"Clarence River Cod, Eastern Freshwater Cod (Maccullochella ikei)",
"Oxleyan Pygmy Perch (Nannoperca oxleyana)",
"Non-parasitic Lamprey (Mordacia praecox)",
"Pugh's Frog (Philoria pughi)",
"Sphagnum Frog (Philoria sphagnicolus)",
"New England treefrog, Glandular Frog (Litoria subglandulosa)",
"Mountain Frog (Philoria kundagungan)",
"Giant Barred Frog, Southern Barred Frog (Mixophyes iteratus)",
"Peppered Tree Frog (Litoria piperata)",
"Stuttering Frog, Southern Barred Frog (Mixophyes balbus)",
"Davies' Tree Frog (Litoria daviesae)",
"Richmond Range Sphagnum Frog (Philoria richmondensis)",
"Fleay's Frog (Mixophyes fleayi)",
"Ellen Clark's Crayfish (Euastacus clarkae)",
"Hairy Cataract Crayfish (Euastacus pilosus)",
"Small Mountain Crayfish (Euastacus simplex)",
"Bloodclaw Crayfish (Euastacus gumar)",
"Small Crayfish (Euastacus spinichelatus)",
"Smooth Crayfish (Euastacus girurmulayn)",
"Hanging Rock Crayfish / Gamilaroi Spiny Crayfish (Euastacus gamilaroi)",
"Blue Black Crayfish (Euastacus jagabar)",
"Leckie's Crayfish (Cherax leckii)",
"Morgan's Crayfish (Euastacus morgani)",
"Mud Gully Crayfish (Euastacus dalagarbe)",
"Dusky Antechinus",
"Eastern Bent-winged Bat",
"Little Bent-winged Bat",
"Hoary Wattled Bat",
"Eastern Pipistrelle",
"Barking Owl",
"Powerful Owl",
"Masked Owl",
"Sooty Owl",
"Fawn-footed Melomy",
"Stephen’s Banded Snake",
"Rufous Bettong",
"Spotted Quail Thrush",
"Coastal Petaltail",
"Palethorpe's Pinwheel Snail (Rhophodon palethorpei)",
"Mottled Grass-skipper (Anisynta cynone anomala)",
"Mount Sebastopol Bristle Snail (Austrochloritis marksandersi)",
"Sunburst Pinwheel Snail (Letomola lanalittleae)",
"Sebastopol Pinwheel Snail (Egilomen sebastopol)",
"Kookaburra Pinwheel Snail (Macleayropa kookaburra)",
"a lace bug (Eritingis trivirgata)",
"Macleay Valley Pinwheel Snail (Gyrocochlea janetwaterhouseae)",
"Boonanghi Pinwheel Snail (Macleayropa boonanghi)",
"Mount Seaview Pinwheel Snail (Elsothera kyliestumkatae)",
"Kippara Forest Bristle Snail (Austrochloritis kippara)",
"a lace bug (Epimixia vulturna)",
"Mount Seaview Bristle Snail (Austrochloritis seaviewensis)",
"Kempsey Copper Pinwheel Snail (Diphyoropa macleayana)",
"Macleay Valley Woodland Snail (Galadistes akubra)",
"Aeluropis Skipper, Mountain Skipper (Mesodina aeluropis)",
"Wauchope Pinwheel Snail (Gyrocochlea wauchope)",
"Lustrous Pinwheel Snail (Rhophodon kempseyensis)",
"Macleay Waxy Pinwheel Snail (Luturopa macleayensis)",
"Nandewar Range Pinwheel Snail (Scelidoropa nandewar)",
"Carrai Pinwheel Snail (Macleayropa carraiensis)",
"Macleay Valley Microturban (Georissa laseroni)",
"Yessabah Caves Bristle Snail (Austrochloritis abbotti)",
"Macleay Valley Goblet-snail, Macleay Valley Droplet-snail (Pleuropoma jana)",
"Dorrigo Carnivorous Snail (Vitellidelos dorrigoensis)",
"Flared White Pinwheel Snail (Discocharopa expandivolva)",
"a spider (Graycassis bruxner)",
"an ant (Tetramorium confusum)",
"Thylacine Darner (Acanthaeschna victoria)",
"a spider (Molycria mammosa)",
"a spider (Graycassis dorrigo)",
"Macksville Bristle Snail (Austrochloritis paucisetosa)",
"a tenebrionid beetle (Coripera morleyana)",
"Eastern Freshwater Shrimp (Australatya striolata)",
"Orange Alpine Xenica; Correa Brown (Oreixenica correae)",
"a spider (Venatrix australiensis)",
"Giant Dragonfly (Petalura gigantea)",
"a spider (Storenosoma terraneum)",
"a spider (Lampona fife)",
"a lucanid beetle (Safrina dekeyzeri)",
"Nandewar Carnivorous Snail (Austrorhytida nandewarensis)",
"Large Riverdamsel (Caliagrion billinghursti)",
"Yessabah Pinwheel Snail (Coenocharopa yessabahensis)",
"Contorted Pinwheel Snail (Letomola contortus)",
"Dingy Darter, Sedge Darter, Southern Sedge Darter (Telicota eurychlora)",
"(Kardomia prominens)",
"(Boronia inflexa subsp torringtonensis)",
"Banyabba Shiny-barked Gum (Eucalyptus pachycalyx subsp. Banyabba)",
"(Cassinia heleniae)",
"(Prostanthera staurophylla)",
"(Macrozamia johnsonii)",
"New England Gentian (Gentiana wissmannii)",
"(Eucalyptus scopulorum)",
"(Olearia oliganthema)",
"Binghi Homoranthus (Homoranthus binghiensis)",
"(Styphelia perileuca)",
"(Acacia beadleana)",
"(Callistemon sp.)",
"(Eucalyptus scopulorum)",
"(Grevillea acanthifolia)",
"(Hibbertia rhynchocalyx)",
"(Olearia sp.)",
"(Pomaderris helianthemifolia)",
"(Prostanthera sp.)",
"(Zieria hindii)",
"(Luzula flaccida subsp.)",
"(Cassinia theodorii)",
"(Juncus laeviusculus)",
"(Allocasuarina defungens)",
"(Astrotricha cordata)",
"(Bertya sp.)",
"(Diuris eborensis)",
"(Eucalyptus pachycalyx subsp. banyabba)",
"(Grevillea guthrieana)",
"(Hakea dohertyi)",
"(Macrozamia johnsonii)",
"(Philotheca obovatifolia)",
"(Zieria floydii)",
"(Almaleea cambagei)",
"(Asterolasia beckersii)",
"(Chiloglottis anaticeps)",
"(Grevillea mollis)",
"(Hibbertia hexandra)",
"(Homoranthus binghiensis)",
"(Melichrus sp. Gibberagee)",
"(Pimelea venosa)",
"(Pterostylis metcalfei)",
"(Triplarina imbricate)",
"(Uromyrtus australis)",
"(Grevillea beadleana)",
"(Macrozamia humilis)",
"(Leucopogon confertus)",
"(Grevillea linsmithii)",
"(Hibbertia marginata)",
"(Prostanthera palustris)"
]
var nswSouthCoastTEC = [
"Upland Basalt Eucalypt Forests of the Sydney Basin Bioregion",
"Alpine Sphagnum Bogs and Associated Fens",
"Illawarra Shoalhaven Subtropical Rainforest",
"Littoral Rainforest and Coastal Vine Thickets of Eastern Australia",
"Robertson Rainforest in the Sydney Basin Bioregion",
"Coastal Swamp Oak (Casuarina glauca) Forest of New South Wales and South East Queensland",
"Shale Sandstone Transition Forest of the Sydney Basin Bioregion",
"Turpentine - Ironbark Forest in the Sydney Basin Bioregion",
"Illawarra and South Coast Lowland Forest and Woodland",
"Lowland Grassy Woodland in the South East Corner Bioregion",
"Southern Highlands Shale Forest and Woodland of the Sydney Basin Bioregion",
"Subtropical and Temperate Coastal Saltmarsh",
"Milton Ulladulla Subtropical Rainforest in the Sydney Basin Bioregion",
"Dry Rainforest of the South East Forests in the South East Corner Bioregion",
"Brogo Wet Vine Forest in the South East Corner Bioregion",
"Freshwater Wetlands on Coastal Floodplains of the New South Wales North Coast, the Sydney Basin and South East Corner Bioregions"
]
var nswSouthCoastSpecies = [
"Littlejohn's Tree Frog, Heath Frog (Litoria littlejohni)",
"Giant Burrowing Frog (Heleioporus australiacus)",
"Stuttering Frog, Southern Barred Frog (in Victoria) (Mixophyes balbus)",
"Northern Corroboree Frog (Pseudophryne pengilleyi)",
"Southern Corroboree Frog (Pseudophryne corroboree)",
"Mustard-bellied Snake (Drysdalia rhodogaster)",
"Broad-headed Snake (Hoplocephalus bungaroides)",
"Guthega Skink (Liopholis guthega)",
"Alpine She-oak Skink (Cyclodomorphus praealtus)",
"Southern Water-skink (Eulamprus tympanum)",
"Glossy Grass Skink, Swampland Cool-skink, Rawlinson's Window-eyed Skink (Pseudemoia rawlinsoni)",
"Southern Leaf-Tailed Gecko, Broad-tailed Gecko (Phyllurus platurus)",
"Stocky Galaxias (Galaxias tantangara)",
"Roundsnout Galaxias (Galaxias terenasus)",
"Non-parasitic Lamprey (Mordacia praecox)",
"Macquarie Perch (Murray-Darling Basin taxa) (Macquaria australasica 'MDB taxa')",
"Blue Mountains Perch (Macquaria sp. nov. 'hawkesbury taxon')",
"Pilotbird (Pycnoptilus floccosus)",
"Eastern Bristlebird (Dasyornis brachypterus)",
"Superb Lyrebird (Menura novaehollandiae)",
"Eastern Ground Parrot (Pezoporus wallicus wallicus)",
"Origma, Rockwarbler (Origma solitaria)",
"Gang-gang Cockatoo (Callocephalon fimbriatum)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Regent Honeyeater (Anthochaera phrygia)",
"Black-faced Monarch (Monarcha melanopsis)",
"Glossy Black-Cockatoo (eastern) (Calyptorhynchus lathami lathami)",
"Dusky Antechinus (Antechinus mimetes)",
"Long-footed Potoroo (Potorous longipes)",
"Long-nosed Potoroo (SE Mainland) (Potorous tridactylus tridactylus)",
"Brush-tailed Rock-wallaby (Petrogale penicillata)",
"Greater Glider (Petauroides volans)",
"Yellow-bellied Glider (Petaurus australis)",
"Spot-tailed Quoll, Spotted-tail Quoll, Tiger Quoll (southeastern mainland population) (Dasyurus maculatus maculatus)",
"Smoky Mouse, Konoom (Pseudomys fumeus)",
"Golden-tipped Bat (Phoniscus papuensis)",
"Platypus (Ornithorhynchus anatinus)",
"Koala (combined populations of Qld, NSW and the ACT) (Phascolarctos cinereus (combined populations of Qld, NSW, ACT))",
"Grey-headed Flying-fox (Pteropus poliocephalus)",
"Broad-toothed Rat (mainland), Tooarrana (Mastacomys fuscus mordicus)",
"New Holland Mouse, Pookila (Pseudomys novaehollandiae)",
"Southern Brown Bandicoot (eastern)",
"Long-nosed Potoroo",
"Eastern Bristlebird",
"Striated Fieldwren",
"Glossy black cockatoo",
"Masked Owl",
"Sooty Owl",
"Powerful Owl",
"Tianjara Crayfish (Euastacus guwinus)",
"Sutton's Crayfish (Euastacus suttoni)",
"Riek's Crayfish (Euastacus rieki)",
"Calyton's Crayfish (Euastacus claytoni)",
"Bidawal Crayfish, East Gippsland Spiny Crayfish (Euastacus bidawalus)",
"Alpine Crayfish (Euastacus crassus)",
"Orbost Spiny Crayfish (Euastacus diversus)",
"Bendathera Pinwheel Snail (Egilodonta bendethera)",
"Bermagui Bristle Snail (Austrochloritis abrotonus)",
"Merimbula Woodland Snail  (Pommerhelix mastersi)",
"Wyanbene Pinwheel Snail  (Egilodonta wyanbenensis)",
"Jervis Bay Forest Snail (Meridolum jervisensis)",
"Lakes Entrance Pinwheel Snail  (Diphyoropa illustra)",
"Koscuiszko Carnivorous Snail (Austrorhytida glaciamans)",
"Prickle Pinhead Snail (Paralaoma annabelli)",
"Jenolan Caves Bristle Snail (Austrochloritis kanangra)",
"Koscuiszko Bristle Snail (Austrochloritis kosciuszkoensis)",
"Blue Mountains Woodland Snail (Pommerhelix monacha)",
"Jewel beetle  (Temognatha rufocyanea)",
"Beetle (Lissapterus grammicus)",
"Beetle ( Aulacopris reichei)",
"Jewel beetle  (Castiarina flavoviridis)",
"Depressed Mussel; Knife-shaped Mussel (Hyridella depressa)",
"Beetle ( Matthewsius illawarrensis)",
"( Venatrix australiensis)",
"Eastern Freshwater Shrimp  (Australatya striolata)",
"Large Riverdamsel (Caliagrion billinghursti)",
"(Asteron grayi )",
"Jewel beetle (Castiarina klugii)",
"Jewel beetle  (Temognatha rufocyanea)",
"Small Alpine Xenica (Oreixenica latialis latialis)",
"(Storenosoma terraneum)",
"Giant Dragonfly  (Petalura gigantea)",
"(Lampona fife)",
"Spider, harvestman or pseudoscorpion  (Molycria mammosa)",
"Jewel beetle  (Castiarina montigena)",
"Mount Kosciusko Wingless Stonefly (Leptoperla cacuminis)",
"Fly (Pelecorhynchus rubidus)",
"Fly (Pelecorhynchus flavipennis)",
"Spotted Alpine Xenica (Oreixenica orichora orichora)",
"Alpine Darner  (Austroaeschna flavomaculata)",
"Glistening Pencil-blue; Common Pencilled-blue (Candalides absimilis edwardsi)",
"Orange Alpine Xenica; Correa Brown (Oreixenica correae)",
"Thylacine Darner (Acanthaeschna victoria)",
"Waterfall Redspot (191 group) (Austropetalia patricia)",
"Green Carpenter Bee, Metallic Green Carpenter Bee, Southern Green Carpenter Bee (Xylocopa aeratus)",
"(Leionema ceratogynum)",
"(Grevillea irrasa subsp. didymochiton)",
"(Leptospermum crassifolium)",
"(Darwinia taxifolia subsp. macrolaena)",
"Budawangs Bushpea  (Pultenaea baeuerlenii)",
"(Grevillea baueri subsp. asperula)",
"Wadbilliga Sticky Boronia  (Boronia anemonifolia subsp. wadbilligensis)",
"(Leionema coxii)",
"Ettrema Mallee  (Eucalyptus sturgissiana)",
"(Boronia subulifolia)",
"Budawangs Cliffheath (Budawangia gnidioides)",
"(Leptospermum subglabratum)",
"Jillaga Ash (Eucalyptus stenostoma)",
"Woila Gum (Eucalyptus olsenii)",
"(Boronia imlayensis)",
"Olsen’s Wattle (Acacia olsenii)",
"Pigeon House Ash, Three-flowered Ash  (Eucalyptus triflora)",
"(Zieria caducibracteata)",
"(Grevillea epicroca)",
"(Leptospermum deuense)",
"(Pomaderris gilmourii var. gilmourii)",
"Jervis Bay Grevillea (Grevillea molyneuxii)",
"Grey Deua Pomaderris  (Pomaderris gilmourii var. cana)",
"Monga Tea-tree  (Leptospermum thompsonii)",
"(Styphelia psiloclada)",
"Mongamulla Mallee  (Eucalyptus deuaensis)",
"Small-leaved Gum (Eucalyptus parvula)",
"(Philotheca scabra subsp. latifolia)",
"(Persoonia mollis subsp. leptophylla)",
"Blay's Wattle (Acacia blayana)",
"(Grevillea aspleniifolia)",
"Wadbilliga Ash  (Eucalyptus paliformis)",
"(Persoonia mollis subsp. budawangensis)",
"Scented Bitter-pea  (Daviesia suaveolens)",
"(Dillwynia crispii)",
"(Hibbertia praemorsa)",
"(Nematolepis elliptica)",
"(Prostanthera tallowa)",
"Bog Grevillea (Grevillea acanthifolia subsp. paludosa)",
"Budawang's Wallaby-grass  (Plinthanthesis rodwayi)",
"Blue Bush, Bluebush, Bendethera Wattle  (Acacia covenyi)",
"Monga Waratah, Braidwood Waratah  (Telopea mongaensis)",
"Pygmy Cypress Pine  (Callitris oblonga subsp. corangensis)",
"Elusive Bush-pea  (Pultenaea elusa)",
"(Dillwynia stipulifera)",
"(Persoonia asperula)",
"(Bursaria calcicola)",
"Superb Midgeorchid  (Genoplesium superbum)",
"Woolly-bear Wattle, Lucas's Wattle (Acacia lucasii)",
"Nowra Heathmyrtle  (Triplarina nowraensis)",
"(Pultenaea rodwayi)",
"White Mountain Ash, White Ash (Eucalyptus fraxinoides)",
"East Lynne Midgeorchid (Genoplesium vernale)",
"(Leptospermum rotundifolium)",
"Velvet Zieria (Zieria murphyi)",
"(Persoonia brevifolia)",
"(Hibbertia circinata)",
"(Schoenus evansianus)",
"(Philotheca myoporoides subsp. brevipedunculata)",
"Narrabarba Wattle (Acacia constablei)",
"Jones Wattle  (Acacia jonesii)",
"Cotoneaster Pomaderris  (Pomaderris cotoneaster)",
"Kydra Dampiera (Dampiera fusca)",
"Bredbo Gentian  (Gentiana bredboensis)",
"Woolly Wattle, Hairy Wattle  (Acacia lanigera var. gracilipes)",
"(Prostanthera saxicola var. montana)",
"(Asterolasia rivularis)",
"(Microlaena stipoides var. breviseta)",
"Macrae's Hakea  (Hakea macraeana)",
"Hamilton's Wattle  (Acacia hamiltoniana)",
"Bantam Bush-pea (Pultenaea parrisiae)",
"(Hibbertia acaulothrix)",
"Dwarf Bottlebrush  (Callistemon subulatus)",
"(Nematolepis rhytidophylla)",
"Genoa Grevillea (Grevillea parvula)",
"Trailing Monotoca  (Monotoca rotundifolia)",
"Wolgan Snow Gum  (Eucalyptus gregsoniana)",
"(Goodenia heterophylla subsp. montana)",
"(Thismia clavarioides)",
"Wiry Flannelflower (Actinotus forsythii)",
"(Dillwynia brunioides)",
"Lemon-scented Zieria  (Zieria citriodora)",
"Imlay Mallee, Mount Imlay Mallee  (Eucalyptus imlayensis)",
"Forrester's Bottlebrush  (Callistemon forresterae)",
"Deane's Boronia  (Boronia deanei)",
"Mountain Banksia (Banksia canei)",
"(Pomaderris gilmourii)",
"Swamp Banksia  (Banksia paludosa subsp. astrolux)",
"(Grevillea imberbis)",
"(Pultenaea vrolandii)",
"Bent Pomaderris  (Pomaderris sericea)",
"Howe Guineaflower  (Hibbertia notabilis)",
"Blue-tongue Greenhood  (Pterostylis oreophila)",
"Jervis Bay Grevillea  (Grevillea macleayana)",
"Leafless Pinkbells  (Tetratheca subaphylla)",
"Mueller’s Cypress  (Callitris muelleri)",
"Olinda Box (Eucalyptus corticosa)",
"(Haloragodendron gibsonii)",
"(Hakea constablei)",
"Tiny Spyridium  (Spyridium cinereum)",
"Camden Woollybutt, Paddys River Box (Eucalyptus macarthurii)",
"Tawny Leekorchid, Slaty Leekorchid (Prasophyllum fuscum)",
"Genoa River Correa (Correa lawrenceana var. genoensis)",
"Blotchy Mintbush  (Prostanthera walteri)",
"(Hakea pachyphylla)",
"Chalker's Wattle (Acacia chalkeri)",
"(Hibbertia saligna)",
"Needle Geebung (Persoonia acerosa)",
"Narrow-leaf Bower Wattle, Sticky Bower Wattle, River Wattle, Bower Wattle  (Acacia subporosa)",
"(Spyridium burragorang)",
"(Almaleea incurvata)",
"Kowmung Hakea (Hakea dohertyi)",
"(Epacris purpurascens var. onosmiflora)",
"Cliff Mallee Ash  (Eucalyptus cunninghamii)",
"(Persoonia mollis subsp. Mollis)",
"(Deyeuxia talariata)",
"Rufous Pomaderris  (Pomaderris brunnea)",
"(Banksia penicillata)",
"Smooth Tea-tree (Leptospermum glabrescens)",
"(Acacia blayana)",
"(Acacia constablei)",
"(Acacia georgensis)",
"(Astrotricha sp. Wallagaraugh)",
"(Boronia anemonifolia subsp. wadbilligensis)",
"(Boronia imlayensis)",
"(Bursaria calcicola)",
"(Darwinia taxifolia)",
"(Eucalyptus imlayensis)",
"(Galium roddii)",
"(Genoplesium plumosum)",
"(Gentiana bredboensis)",
"(Grevillea acanthifolia)",
"(Grevillea aspleniifolia)",
"(Grevillea irrasa subsp. irrasa)",
"(Grevillea rhyolitica)",
"(Hibbertia circinata)",
"(Hibbertia praemorsa)",
"(Juncus laeviusculus)",
"(Leionema ceratogynum)",
"(Leptospermum crassifolium)",
"(Nematolepis rhytidophylla)",
"(Pimelea bracteata)",
"(Plinthanthesis rodwayi)",
"(Pomaderris gilmourii)",
"(Prasophyllum innubum)",
"(Pterostylis oreophila)",
"(Pultenaea elusa)",
"(Thismia clavarioides)",
"(Zieria adenophora)",
"(Zieria citriodora)"
];
var SEQLDTEC = ["Lowland Rainforest of Subtropical Australia",
    "White Box-Yellow Box-Blakely's Red Gum Grassy Woodland and Derived Native Grassland", "Gondwana Rainforests of Australia World Heritage Area", "Moreton Bay Ramsar Wetland", "Great Sandy National Park"
    ]
var SEQLDSpecies = [
"Honey Blue-eye (Pseudomugil mellis)",
"Oxleyan Pygmy Perch (Nannoperca oxleyana)",
"Fleay's Frog (Mixophyes fleayi)",
"Non-parasitic Lamprey (Mordacia praecox)",
"Rainforest Cool-skink (Harrisoniascincus zia)",
"Three-toed Snake-tooth Skink (Coeranoscincus reticulatus)",
"Albert's Lyrebird (Menura alberti)",
"Hastings River Mouse, Koontoo (Pseudomys oralis)",
"Rufous Scrub-bird (Atrichornis rufescens)",
"Mountain Frog (Philoria kundagungan)",
"Brush-tailed Rock-wallaby (Petrogale penicillata)",
"Spot-tailed Quoll, Spotted-tail Quoll, Tiger Quoll (Dasyurus maculatus)",
"New Holland Mouse, Pookila (Pseudomys novaehollandiae)",
"Regent Honeyeater (Anthochaera phrygia)",
"Glossy Black-Cockatoo (eastern) (Calyptorhynchus lathami)",
"Black-faced Monarch (Monarcha melanopsis)",
"Koala (Phascolarctos cinereus)",
"Yellow-bellied Glider (Petaurus australis)",
"Golden-tipped Bat (Phoniscus papuensis)",
"Grey-headed Flying-fox (Pteropus poliocephalus)",
"Platypus (Ornithorhynchus anatinus)",
"Long-nosed Potoroo (Potorous tridactylus)",
"Greater Glider (Petauroides volans)",
"Eastern Ground Parrot (Pezoporus wallicus)",
"Giant Barred Frog (Mixophyes iteratus)",
"Eastern Bristlebird (Dasyornis brachypterus)",
"Red-browed Treecreeper (Climacteris erythrops)",
"Dusky Antechinus (Antechinus mimetes)",
"Parma Wallaby (Notamacropus parma)",
"ground parrot (Pezoporus wallicus)",
"southern emu-wren (Stipiturus malachurus)",
"wallum froglet (Crinia tinnula)",
"wallum rocketfrog (Litoria freycineti)",
"red-and-yellow mountain frog (Philoria kundagungan)",
"Freshwater crayfish (Euastacus jagara)",
"Eastern Freshwater Shrimp (Australatya striolata)",
"Large Riverdamsel (Caliagrion Billinghursti)",
"A spider (Asteron grayi)",
"A spider (Molycria mammosa)",
"Mt Barney bertya-shrub (Bertya ernestiana)",
"Mountain Wax-flower (Philotheca obovatifolia)",
"Mountain Zieria (Zieria montana)",
"Linsmith's Grevillea (Grevillea linsmithii)",
"Lamington Eyebright, Mt Merino Eyebright (Euphrasia bella)",
"(Prostanthera caerulea)",
"Swamp Mint-bush (Prostanthera palustris)",
"Three-nerved Wattle (Acacia trinervata)",
"Christmas bells (Blandfordia grandiflora)",
"Binna Burra daisy (Brachyscome ascendens)",
"wax orchid (Bulbophyllum weinthalii subsp. weinthalii)",
"mallee ash (Eucalyptus codonocarpa)",
"Dunn's white gum (Eucalyptus dunni)",
"(Gonocarpus hirtus)",
"(Leptospermum barneyense)",
"(Pimelea umbratica)",
"(Pseudanthus pauciflorus subsp. pauciflorus)",
"(Tetramolopium vagans)",
"(Zieria montana)"
];

// Loading to new Mus
addTsToMus(["Alpine Bushfire"], alpineTEC, "Other TEC");
// Alpine species
addTsToMus(["Alpine Bushfire"], alpineSpecies, "Other Species");
// Greater Blue Mountains TEC
addTsToMus(["Greater Blue Mountains Bushfire"], greaterTEC, "Other TEC");
// Geater Blue Mountains Species
addTsToMus(["Greater Blue Mountains Bushfire"], greaterSpecies, "Other Species");
// East Gippsland Species
addTsToMus(["East Gippsland Bushfire"], eastGippslandSpecies, "Other Species");
// Kangaroo island Species
addTsToMus(["Kangaroo Island Bushfire"], kangarooIslandSpecies, "Other Species");

// NSW North Coast And TableLand TEC
addTsToMus(["NSW North Coast And Tablelands Bushfire"], northCoastAndTableLandsTEC, "Other TEC");
// NSW North Coast And TableLand Species
addTsToMus(["NSW North Coast And Tablelands Bushfire"], northCoastAndTableLandsSpecies, "Other Species")
// NSW South Coast TEC
addTsToMus(["NSW South Coast Bushfire"], nswSouthCoastTEC, "Other TEC")
// NSW South Coast Species
addTsToMus(["NSW South Coast Bushfire"], nswSouthCoastSpecies, "Other Species")
// SEQLD TEC
addTsToMus(["South-East Queensland Bushfire"], SEQLDTEC, "Other TEC")

// SEQLD Species
addTsToMus(["South-East Queensland Bushfire"], SEQLDSpecies, "Other Species")



// Loading to RLP Mu's

addTsToMus(["Riverina"], alpineTEC, "Other TEC");
addTsToMus(["Riverina"], alpineSpecies, "Other Species");

addTsToMus(["South East NSW"], alpineTEC, "Other TEC");
addTsToMus(["South East NSW"], alpineSpecies, "Other Species");

addTsToMus(["ACT"], alpineTEC, "Other TEC");
addTsToMus(["ACT"], alpineSpecies, "Other Species");

addTsToMus(["Murray"], alpineTEC, "Other TEC");
addTsToMus(["Murray"], alpineSpecies, "Other Species");

addTsToMus(["North East"], alpineTEC, "Other TEC");
addTsToMus(["North East"], alpineSpecies, "Other Species");

addTsToMus(["Hunter"], greaterTEC, "Other TEC");
addTsToMus(["Hunter"], greaterSpecies, "Other Species");

addTsToMus(["Central Tablelands"], greaterTEC, "Other TEC");
addTsToMus(["Central Tablelands"], greaterSpecies, "Other Species");

addTsToMus(["Greater Sydney"], greaterTEC, "Other TEC");
addTsToMus(["Greater Sydney"], greaterSpecies, "Other Species");

addTsToMus(["East Gippsland"], eastGippslandSpecies, "Other Species");

addTsToMus(["Kangaroo Island"], kangarooIslandSpecies, "Other Species");

addTsToMus(["North Coast"], northCoastAndTableLandsTEC, "Other TEC");
addTsToMus(["North Coast"], northCoastAndTableLandsSpecies, "Other Species");

addTsToMus(["Northern Tablelands"], northCoastAndTableLandsTEC, "Other TEC");
addTsToMus(["Northern Tablelands"], northCoastAndTableLandsSpecies, "Other Species");

addTsToMus(["South East Queensland"], SEQLDTEC, "Other TEC");
addTsToMus(["South East Queensland"], SEQLDSpecies, "Other Species");
