apply plugin:"jacoco"
jacoco {
    toolVersion = "0.8.8"
}
test {
    useJUnitPlatform()
    jacoco {
        excludes = ['**/Application.groovy',
                    '**/BootStrap.groovy',
                    '**/UrlMappings.groovy',
                    '**/*GrailsPlugin.groovy',
                    '**/*Mock.groovy',
                    'com.skedgo.converter.*']
    }
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn check

    finalizedBy jacocoTestCoverageVerification
    afterEvaluate {
        getClassDirectories().setFrom(classDirectories.files.collect {
            fileTree(dir: it,
                    exclude: [
                            '**/TimezoneMapper.class'
                    ]
            )
        })
    }
    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('reports/jacocoHtml')
    }
}

jacocoTestCoverageVerification {
    dependsOn test
    violationRules {
        rule {
            limit {
                minimum = 0.1
            }
        }
    }
}