load("./unsetUserPermissionVersion.js");
load("./changeReportDoubleToIntegers.js");
load("./updateEmptyGeoIndex.js");
load("./updateUndefinedValues.js");
load("./updateDocumentDateTaken.js");
load("./updateProgramConfig.js");
load("./updateActivityFormVersionDoubleToInt.js");
load("./updateEventDates.js");
load("./fixProjectIndexing.js");
load("./updateAuditEntityIds.js");
print("Migration complete");